"use client";
import { FormEvent, useState } from "react";
import { authClient } from "@/lib/auth-client";
import type { CurrentUser } from "@/lib/auth/current-user";

export function AccountSettings({ user }: { user: CurrentUser }) {
  const [values, setValues] = useState({ current: "", password: "", confirm: "" }); const [pending, setPending] = useState(false); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setStatus(""); if (values.password.length < 8) return setError("New password must be at least 8 characters."); if (values.password !== values.confirm) return setError("Passwords do not match."); setPending(true); const result = await authClient.changePassword({ currentPassword: values.current, newPassword: values.password, revokeOtherSessions: true }); setPending(false); if (result.error) return setError("Current password is incorrect or the password could not be changed."); setValues({ current: "", password: "", confirm: "" }); setStatus("Password changed. Other sessions have been signed out."); }
  return <div className="settings-stack"><section className="panel"><h2>Profile</h2><dl className="profile-details"><div><dt>Display name</dt><dd>{user.name}</dd></div><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Role</dt><dd><span className="badge">{user.role}</span></dd></div></dl></section><section className="panel"><h2>Change password</h2><form className="settings-form" onSubmit={submit}><label className="field"><span>Current password</span><input type="password" autoComplete="current-password" required value={values.current} onChange={(e) => setValues({ ...values, current: e.target.value })}/></label><label className="field"><span>New password</span><input type="password" minLength={8} autoComplete="new-password" required value={values.password} onChange={(e) => setValues({ ...values, password: e.target.value })}/></label><label className="field"><span>Confirm new password</span><input type="password" minLength={8} autoComplete="new-password" required value={values.confirm} onChange={(e) => setValues({ ...values, confirm: e.target.value })}/></label>{error && <p className="form-error">{error}</p>}{status && <p className="form-success">{status}</p>}<button className="button" disabled={pending}>{pending ? "Changing…" : "Change password"}</button></form></section></div>;
}
