"use client";
import Link from "next/link";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { authClient } from "@/lib/auth-client";

function AuthBrand() { return <div className="auth-brand"><Image src="/HerbOverflow.png" alt="" width={36} height={36}/><span>Herb Overflow</span></div>; }
function message(error: { message?: string } | null | undefined, fallback: string) { return error?.message && !/database|internal|sql|stack/i.test(error.message) ? error.message : fallback; }

export function LoginForm() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (pending) return; setPending(true); setError(""); const result = await authClient.signIn.email({ email: email.trim().toLowerCase(), password, callbackURL: "/" }); setPending(false); if (result.error) return setError("The email or password is incorrect."); window.location.assign("/"); }
  return <AuthCard title="Welcome back" subtitle="Sign in to continue to your shared pharmacognosy workspace."><div className="auth-context"><LockKeyhole size={16}/><span>Private, invite-only workspace</span></div><form onSubmit={submit} className="auth-form"><Field label="Email"><div className="auth-input-wrap"><Mail size={17}/><input type="email" inputMode="email" autoCapitalize="none" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)}/></div></Field><Field label="Password"><div className="auth-input-wrap"><LockKeyhole size={17}/><input type={showPassword ? "text" : "password"} autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)}/><button type="button" className="password-toggle" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></Field>{error && <p className="form-error" role="alert" aria-live="polite">{error}</p>}<button className="button auth-submit" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button><div className="auth-divider"><span>New to Herb Overflow?</span></div><Link className="button secondary" href="/signup">Create an invited account</Link><p className="auth-help">Registration requires an invitation from an administrator. Contact an administrator if you need your password reset.</p></form></AuthCard>;
}

export function SignupForm() {
  const [values, setValues] = useState({ name: "", email: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [complete, setComplete] = useState(false);
  function set(key: keyof typeof values, value: string) { setValues((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (values.name.trim().length < 2) return setError("Enter a display name."); if (values.password.length < 8) return setError("Password must be at least 8 characters."); if (values.password !== values.confirm) return setError("Passwords do not match."); if (pending) return; setPending(true); const response = await fetch("/api/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.name, email: values.email, password: values.password, confirmPassword: values.confirm }) }); const result = await response.json().catch(() => ({})); setPending(false); if (!response.ok) return setError(message(result, "Unable to create this account. Confirm that your invitation is valid.")); setComplete(true); }
  if (complete) return <AuthCard title="Account ready" subtitle="Your invited account has been created. You can sign in immediately."><Link className="button" href="/login">Sign in</Link></AuthCard>;
  return <AuthCard title="Create your account" subtitle="Herb Overflow is invite-only. Use the email address your invitation was issued to."><form onSubmit={submit} className="auth-form"><Field label="Display name"><input autoComplete="name" required value={values.name} onChange={(e) => set("name", e.target.value)}/></Field><Field label="Email"><input type="email" autoComplete="email" required value={values.email} onChange={(e) => set("email", e.target.value)}/></Field><Field label="Password"><input type="password" minLength={8} autoComplete="new-password" required value={values.password} onChange={(e) => set("password", e.target.value)}/></Field><Field label="Confirm password"><input type="password" minLength={8} autoComplete="new-password" required value={values.confirm} onChange={(e) => set("confirm", e.target.value)}/></Field>{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button><p className="auth-foot">Already registered? <Link href="/login">Sign in</Link></p></form></AuthCard>;
}

function AuthCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="auth-card"><AuthBrand/><div><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="auth-field"><span>{label}</span>{children}</label>; }
