"use client";
import Link from "next/link";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { authClient } from "@/lib/auth-client";

function AuthBrand() { return <div className="auth-brand"><Image src="/HerbOverflow.png" alt="" width={36} height={36}/><span>Herb Overflow</span></div>; }
function message(error: { message?: string } | null | undefined, fallback: string) { return error?.message && !/database|internal|sql|stack/i.test(error.message) ? error.message : fallback; }

export function LoginForm() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [needsVerification, setNeedsVerification] = useState(false); const [pending, setPending] = useState(false); const [resent, setResent] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (pending) return; setPending(true); setError(""); setNeedsVerification(false); setResent(false); const result = await authClient.signIn.email({ email: email.trim().toLowerCase(), password, callbackURL: "/" }); setPending(false); if (result.error) { const unverified = result.error.status === 403 && /verif/i.test(result.error.message ?? ""); setNeedsVerification(unverified); return setError(unverified ? "Your account exists, but the email address still needs to be verified." : "The email or password is incorrect."); } window.location.assign("/"); }
  async function resend() { if (pending) return; setPending(true); const result = await authClient.sendVerificationEmail({ email: email.trim().toLowerCase(), callbackURL: "/" }); setPending(false); if (result.error) return setError("The verification email could not be sent. Check the server email configuration."); setResent(true); }
  return <AuthCard title="Welcome back" subtitle="Sign in to continue to your shared pharmacognosy workspace."><div className="auth-context"><LockKeyhole size={16}/><span>Private, invite-only workspace</span></div><form onSubmit={submit} className="auth-form"><Field label="Email"><div className="auth-input-wrap"><Mail size={17}/><input type="email" inputMode="email" autoCapitalize="none" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)}/></div></Field><Field label="Password"><div className="auth-input-wrap"><LockKeyhole size={17}/><input type={showPassword ? "text" : "password"} autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)}/><button type="button" className="password-toggle" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></Field><div className="auth-row"><Link href="/forgot-password">Forgot password?</Link></div>{error && <p className="form-error" role="alert" aria-live="polite">{error}</p>}<button className="button auth-submit" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button>{needsVerification && <button className="button secondary" type="button" onClick={resend} disabled={pending || resent}>{resent ? "Verification email sent" : "Resend verification email"}</button>}<div className="auth-divider"><span>New to Herb Overflow?</span></div><Link className="button secondary" href="/signup">Create an invited account</Link><p className="auth-help">Registration requires an invitation from an administrator.</p></form></AuthCard>;
}

export function SignupForm() {
  const [values, setValues] = useState({ name: "", email: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [complete, setComplete] = useState<"verify" | "ready" | null>(null);
  function set(key: keyof typeof values, value: string) { setValues((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (values.name.trim().length < 2) return setError("Enter a display name."); if (values.password.length < 8) return setError("Password must be at least 8 characters."); if (values.password !== values.confirm) return setError("Passwords do not match."); if (pending) return; setPending(true); const response = await fetch("/api/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.name, email: values.email, password: values.password, confirmPassword: values.confirm }) }); const result = await response.json().catch(() => ({})); setPending(false); if (!response.ok) return setError(message(result, "Unable to create this account. Confirm that your invitation is valid.")); setComplete(result.emailVerificationRequired === false ? "ready" : "verify"); }
  if (complete === "ready") return <AuthCard title="Account ready" subtitle="Your local development account has been created. Email verification remains required in production."><Link className="button" href="/">Enter Herb Overflow</Link></AuthCard>;
  if (complete === "verify") return <AuthCard title="Check your email" subtitle="We sent a verification link to your email address. Verify it before entering Herb Overflow."><Link className="button" href="/login">Back to sign in</Link></AuthCard>;
  return <AuthCard title="Create your account" subtitle="Herb Overflow is invite-only. Use the email address your invitation was issued to."><form onSubmit={submit} className="auth-form"><Field label="Display name"><input autoComplete="name" required value={values.name} onChange={(e) => set("name", e.target.value)}/></Field><Field label="Email"><input type="email" autoComplete="email" required value={values.email} onChange={(e) => set("email", e.target.value)}/></Field><Field label="Password"><input type="password" minLength={8} autoComplete="new-password" required value={values.password} onChange={(e) => set("password", e.target.value)}/></Field><Field label="Confirm password"><input type="password" minLength={8} autoComplete="new-password" required value={values.confirm} onChange={(e) => set("confirm", e.target.value)}/></Field>{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button><p className="auth-foot">Already registered? <Link href="/login">Sign in</Link></p></form></AuthCard>;
}

export function ForgotPasswordForm() {
  const [email, setEmail] = useState(""); const [pending, setPending] = useState(false); const [complete, setComplete] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (pending) return; setPending(true); await authClient.requestPasswordReset({ email: email.trim().toLowerCase(), redirectTo: "/reset-password" }); setPending(false); setComplete(true); }
  return <AuthCard title="Reset your password" subtitle="Enter your email and we’ll send reset instructions if an account exists.">{complete ? <><p className="auth-notice">If an account exists for this email, a password reset link has been sent.</p><Link className="button" href="/login">Back to sign in</Link></> : <form onSubmit={submit} className="auth-form"><Field label="Email"><input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)}/></Field><button className="button" disabled={pending}>{pending ? "Sending…" : "Send reset link"}</button><p className="auth-foot"><Link href="/login">Back to sign in</Link></p></form>}</AuthCard>;
}

export function ResetPasswordForm({ token, invalid }: { token?: string; invalid?: boolean }) {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(invalid ? "This reset link is invalid or expired." : ""); const [pending, setPending] = useState(false); const [complete, setComplete] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!token) return setError("This reset link is invalid or expired."); if (password.length < 8) return setError("Password must be at least 8 characters."); if (password !== confirm) return setError("Passwords do not match."); setPending(true); const result = await authClient.resetPassword({ newPassword: password, token }); setPending(false); if (result.error) return setError("This reset link is invalid or expired."); setComplete(true); }
  if (complete) return <AuthCard title="Password updated" subtitle="Your password has been reset and existing sessions have been revoked."><Link className="button" href="/login">Sign in</Link></AuthCard>;
  return <AuthCard title="Choose a new password" subtitle="Use at least 8 characters."><form onSubmit={submit} className="auth-form"><Field label="New password"><input type="password" minLength={8} autoComplete="new-password" required value={password} onChange={(e) => setPassword(e.target.value)}/></Field><Field label="Confirm new password"><input type="password" minLength={8} autoComplete="new-password" required value={confirm} onChange={(e) => setConfirm(e.target.value)}/></Field>{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={pending || !token}>{pending ? "Updating…" : "Update password"}</button></form></AuthCard>;
}

function AuthCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="auth-card"><AuthBrand/><div><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="auth-field"><span>{label}</span>{children}</label>; }
