"use client";
import { CheckCircle2, Download, FileArchive, RotateCcw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { downloadFullBackup, preRestoreFilename, type BackupDownloadProgress } from "@/lib/backup/client";

type Policy = { enabled: boolean; frequency: "daily" | "weekly"; time: string; timezone: string; catchUp: boolean; lastSuccessfulLocalBackupAt: string | null; lastAttemptAt: string | null; lastAttemptPeriodKey: string | null };
type Schedule = { overdue: boolean; dueAt: string | null; nextAt: string | null; periodKey: string | null };
type PreviewDrug = { id: string; koreanName: string; catalogIndex: number | null; referenceIndex: number | null; exists: boolean; fields: { key: string; label: string }[]; warnings: string[] };
type Preview = { manifest: { createdAt: string; media: { count: number; bytes: number } }; drugs: PreviewDrug[] };

export function BackupSettings() {
  const [policy, setPolicy] = useState<Policy>(); const [schedule, setSchedule] = useState<Schedule>();
  const [status, setStatus] = useState<string>(); const [error, setError] = useState<string>();
  const [busy, setBusy] = useState<"backup" | "safety" | "restore">();
  const [progress, setProgress] = useState<BackupDownloadProgress>();
  const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<Preview>();
  const [query, setQuery] = useState(""); const [selection, setSelection] = useState<Record<string, string[]>>({});
  const [safetyToken, setSafetyToken] = useState<string>(); const [result, setResult] = useState<string>();
  useEffect(() => { fetch("/api/backup/policy", { cache: "no-store" }).then((response) => response.json()).then((data) => { setPolicy(data.policy); setSchedule(data.schedule); }).catch(() => setError("백업 설정을 불러오지 못했습니다.")); }, []);
  async function savePolicy() { if (!policy) return; setError(undefined); const response = await fetch("/api/backup/policy", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: policy.enabled, frequency: policy.frequency, time: policy.time, timezone: policy.timezone, catchUp: policy.catchUp }) }); const body = await response.json(); if (!response.ok) { setError(typeof body.error === "string" ? body.error : "설정을 저장하지 못했습니다."); return; } setPolicy(body.policy); setSchedule(body.schedule); setStatus("백업 정책 저장됨"); }
  async function backupNow() { setError(undefined); setBusy("backup"); setProgress({ phase: "preparing", loaded: 0, total: null }); setStatus("백업 준비 중"); try { const attempt = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "attempt" }) }); if (!attempt.ok) throw new Error("백업 시도를 등록하지 못했습니다."); const saved = await downloadFullBackup(undefined, (next) => { setProgress(next); setStatus(progressLabel(next)); }); setStatus(`다운로드 시작됨 · ${formatBytes(saved.size)}`); const response = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "success" }) }); const body = await response.json(); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "로컬 백업 전달 상태를 기록하지 못했습니다."); setPolicy(body.policy); setSchedule(body.schedule); setProgress({ phase: "saving", loaded: saved.size, total: saved.size }); } catch (caught) { setStatus("백업 실패"); setError(caught instanceof Error ? caught.message : "백업에 실패했습니다."); setProgress(undefined); } finally { setBusy(undefined); } }
  async function chooseBackup(next?: File) { setFile(next); setPreview(undefined); setSelection({}); setSafetyToken(undefined); setResult(undefined); setError(undefined); if (!next) return; const form = new FormData(); form.append("file", next); const response = await fetch("/api/restore/preview", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "백업을 검증하지 못했습니다."); return; } setPreview(body); }
  function toggleField(drugId: string, field: string) { setSafetyToken(undefined); setSelection((current) => { const fields = new Set(current[drugId] ?? []); if (fields.has(field)) fields.delete(field); else fields.add(field); const next = { ...current, [drugId]: [...fields] }; if (!fields.size) delete next[drugId]; return next; }); }
  function toggleDrug(drug: PreviewDrug) { setSafetyToken(undefined); setSelection((current) => current[drug.id]?.length ? Object.fromEntries(Object.entries(current).filter(([id]) => id !== drug.id)) : { ...current, [drug.id]: drug.fields.map((field) => field.key) }); }
  const selectedCount = Object.keys(selection).length;
  async function safetyBackup() { setError(undefined); setBusy("safety"); setProgress({ phase: "preparing", loaded: 0, total: null }); setStatus("복원 전 안전 백업 준비 중"); try { const saved = await downloadFullBackup(preRestoreFilename(), (next) => { setProgress(next); setStatus(progressLabel(next, true)); }); if (!saved.size) throw new Error("사전 안전 백업이 비어 있습니다."); const response = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "safety" }) }); const body = await response.json(); if (!response.ok || !body.token) throw new Error("안전 백업 확인 토큰을 만들지 못했습니다."); setSafetyToken(body.token); setStatus("복원 전 안전 백업 다운로드 시작됨"); } catch (caught) { setSafetyToken(undefined); setStatus("안전 백업 실패"); setError(caught instanceof Error ? caught.message : "사전 안전 백업에 실패했습니다."); setProgress(undefined); } finally { setBusy(undefined); } }
  async function restore() { if (!file || !safetyToken || !selectedCount || !window.confirm(`선택한 Data Card ${selectedCount}개의 필드를 백업 상태로 교체할까요?`)) return; setError(undefined); setBusy("restore"); setStatus("복원 중"); const form = new FormData(); form.append("file", file); form.append("safetyToken", safetyToken); form.append("selections", JSON.stringify(Object.entries(selection).map(([drugId, fields]) => ({ drugId, fields })))); try { const response = await fetch("/api/restore/commit", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "복원에 실패했습니다."); setSafetyToken(undefined); setStatus("복원 실패"); return; } setResult(`${body.restored}개 Data Card 복원 · 미디어 ${body.mediaRestored}개 복구`); setStatus("복원 완료"); setSafetyToken(undefined); } finally { setBusy(undefined); } }
  const visible = useMemo(() => preview?.drugs.filter((drug) => drug.koreanName.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())) ?? [], [preview, query]);
  return <>
    <section className="settings-section panel backup-panel" id="backup"><div className="settings-section-heading"><h2>Backup</h2><p>전체 콘텐츠와 실제 이미지 파일을 하나의 로컬 ZIP으로 저장합니다. 인증 비밀은 포함하지 않습니다.</p></div>
      {policy ? <div className="backup-policy-grid"><label><span>Automatic local backup</span><input type="checkbox" checked={policy.enabled} onChange={(event) => setPolicy({ ...policy, enabled: event.target.checked })}/></label><label><span>Frequency</span><select value={policy.frequency} onChange={(event) => setPolicy({ ...policy, frequency: event.target.value as Policy["frequency"] })}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label><span>Scheduled time</span><input type="time" value={policy.time} onChange={(event) => setPolicy({ ...policy, time: event.target.value })}/></label><label><span>Timezone</span><input value={policy.timezone} onChange={(event) => setPolicy({ ...policy, timezone: event.target.value })}/></label><label><span>Missed backup catch-up</span><input type="checkbox" checked={policy.catchUp} onChange={(event) => setPolicy({ ...policy, catchUp: event.target.checked })}/></label></div> : <p className="muted">백업 정책을 불러오는 중…</p>}
      <div className="backup-status-grid"><span>마지막 로컬 백업<strong>{date(policy?.lastSuccessfulLocalBackupAt)}</strong></span><span>마지막 시도<strong>{date(policy?.lastAttemptAt)}</strong></span><span>다음 예정 백업<strong>{policy?.enabled ? date(schedule?.nextAt) : "자동 백업 꺼짐"}</strong></span><span>상태<strong className={backupState(policy, schedule).tone}>{backupState(policy, schedule).label}</strong></span></div>
      {error ? <p className="form-error" role="alert">{error}</p> : null}{status ? <div className="backup-progress" aria-live="polite"><div><span>{status}</span><strong>{progressPercent(progress)}</strong></div><progress max="100" value={progressValue(progress)}/>{progress?.phase === "preparing" ? <small>데이터와 사용 중인 이미지의 무결성을 확인하고 ZIP을 생성하고 있습니다.</small> : null}</div> : null}<div className="backup-actions"><button className="button secondary" disabled={Boolean(busy)} onClick={() => void savePolicy()}>정책 저장</button><button className="button" disabled={Boolean(busy)} onClick={() => void backupNow()}><Download size={15}/> {busy === "backup" ? "백업 중…" : "지금 백업"}</button></div>
    </section>
    <section className="settings-section panel restore-panel" id="restore"><div className="settings-section-heading"><h2>Restore</h2><p>로컬 HerbOverflow 백업에서 선택한 Data Card 또는 필드만 복구합니다.</p></div><label className="button secondary restore-file-button"><FileArchive size={15}/> 백업 파일 선택<input type="file" accept=".zip,application/zip" hidden onChange={(event) => void chooseBackup(event.target.files?.[0])}/></label>
      {preview ? <div className="restore-preview"><header><span><strong>{preview.drugs.length} Data Cards</strong><small>{new Date(preview.manifest.createdAt).toLocaleString("ko-KR")} · media {preview.manifest.media.count}</small></span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="생약 검색"/></header><div className="restore-drug-list">{visible.map((drug) => <article key={drug.id} className={!drug.exists ? "unavailable" : ""}><label><input type="checkbox" disabled={!drug.exists} checked={Boolean(selection[drug.id]?.length)} onChange={() => toggleDrug(drug)}/><strong>{drug.koreanName}</strong><small>{drug.exists ? `${selection[drug.id]?.length ?? 0}/${drug.fields.length} fields` : "현재 DB에 없음"}</small></label>{selection[drug.id]?.length ? <div className="restore-fields">{drug.fields.map((field) => <label key={field.key}><input type="checkbox" checked={selection[drug.id]?.includes(field.key) ?? false} onChange={() => toggleField(drug.id, field.key)}/>{field.label}</label>)}</div> : null}{drug.warnings.map((warning) => <p key={warning}>{warning}</p>)}</article>)}</div><footer><span>{selectedCount}개 Data Card 선택</span>{!safetyToken ? <button className="button secondary" disabled={!selectedCount || Boolean(busy)} onClick={() => void safetyBackup()}><ShieldCheck size={15}/> {busy === "safety" ? "안전 백업 중…" : "사전 안전 백업"}</button> : <button className="button" disabled={Boolean(busy)} onClick={() => void restore()}><RotateCcw size={15}/> {busy === "restore" ? "복원 중…" : "복원 실행"}</button>}</footer></div> : null}
      {result ? <p className="form-success"><CheckCircle2 size={15}/> {result}</p> : null}
    </section>
  </>;
}

function date(value?: string | null) { return value ? new Date(value).toLocaleString("ko-KR") : "—"; }
function formatBytes(value: number) { return value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`; }
function progressValue(progress?: BackupDownloadProgress) { if (!progress) return 0; if (progress.phase === "preparing") return 12; if (progress.phase === "saving") return 100; return progress.total ? Math.max(15, Math.round(progress.loaded / progress.total * 100)) : 65; }
function progressPercent(progress?: BackupDownloadProgress) { return progress?.phase === "downloading" && progress.total ? `${Math.round(progress.loaded / progress.total * 100)}%` : progress?.phase === "saving" ? "100%" : ""; }
function progressLabel(progress: BackupDownloadProgress, safety = false) { const prefix = safety ? "안전 백업" : "백업"; if (progress.phase === "preparing") return `${prefix} ZIP 생성 중`; if (progress.phase === "saving") return `${prefix} 파일 저장 준비 완료`; return progress.total ? `${prefix} 다운로드 중 · ${formatBytes(progress.loaded)} / ${formatBytes(progress.total)}` : `${prefix} 다운로드 중 · ${formatBytes(progress.loaded)}`; }
function backupState(policy?: Policy, schedule?: Schedule) {
  if (!policy) return { label: "확인 중…", tone: "" };
  const attempted = policy.lastAttemptAt ? new Date(policy.lastAttemptAt).getTime() : 0;
  const succeeded = policy.lastSuccessfulLocalBackupAt ? new Date(policy.lastSuccessfulLocalBackupAt).getTime() : 0;
  if (attempted > succeeded) return { label: "마지막 시도 실패", tone: "failed" };
  if (!policy.enabled) return { label: "자동 백업 꺼짐", tone: "disabled" };
  if (schedule?.overdue) return { label: "백업 필요", tone: "overdue" };
  if (succeeded) return { label: "최신", tone: "healthy" };
  return { label: "백업 기록 없음", tone: "" };
}
