"use client";
import { CheckCircle2, Download, FileArchive, RotateCcw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { downloadFullBackup, preRestoreFilename } from "@/lib/backup/client";

type Policy = { enabled: boolean; frequency: "daily" | "weekly"; time: string; timezone: string; catchUp: boolean; lastSuccessfulLocalBackupAt: string | null; lastAttemptAt: string | null; lastAttemptPeriodKey: string | null };
type Schedule = { overdue: boolean; dueAt: string | null; nextAt: string | null; periodKey: string | null };
type PreviewDrug = { id: string; koreanName: string; catalogIndex: number | null; referenceIndex: number | null; exists: boolean; fields: { key: string; label: string }[]; warnings: string[] };
type Preview = { manifest: { createdAt: string; media: { count: number; bytes: number } }; drugs: PreviewDrug[] };

export function BackupSettings() {
  const [policy, setPolicy] = useState<Policy>(); const [schedule, setSchedule] = useState<Schedule>();
  const [status, setStatus] = useState<string>(); const [error, setError] = useState<string>();
  const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<Preview>();
  const [query, setQuery] = useState(""); const [selection, setSelection] = useState<Record<string, string[]>>({});
  const [safetyToken, setSafetyToken] = useState<string>(); const [result, setResult] = useState<string>();
  useEffect(() => { fetch("/api/backup/policy", { cache: "no-store" }).then((response) => response.json()).then((data) => { setPolicy(data.policy); setSchedule(data.schedule); }).catch(() => setError("백업 설정을 불러오지 못했습니다.")); }, []);
  async function savePolicy() { if (!policy) return; setError(undefined); const response = await fetch("/api/backup/policy", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: policy.enabled, frequency: policy.frequency, time: policy.time, timezone: policy.timezone, catchUp: policy.catchUp }) }); const body = await response.json(); if (!response.ok) { setError(typeof body.error === "string" ? body.error : "설정을 저장하지 못했습니다."); return; } setPolicy(body.policy); setSchedule(body.schedule); setStatus("백업 정책 저장됨"); }
  async function backupNow() { setError(undefined); setStatus("Generating"); try { const attempt = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "attempt" }) }); if (!attempt.ok) throw new Error("백업 시도를 등록하지 못했습니다."); setStatus("Downloading"); const saved = await downloadFullBackup(); setStatus(`Local save initiated · ${formatBytes(saved.size)}`); const response = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "success" }) }); const body = await response.json(); if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "로컬 백업 전달 상태를 기록하지 못했습니다."); setPolicy(body.policy); setSchedule(body.schedule); } catch (caught) { setStatus("Failed"); setError(caught instanceof Error ? caught.message : "백업에 실패했습니다."); } }
  async function chooseBackup(next?: File) { setFile(next); setPreview(undefined); setSelection({}); setSafetyToken(undefined); setResult(undefined); setError(undefined); if (!next) return; const form = new FormData(); form.append("file", next); const response = await fetch("/api/restore/preview", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "백업을 검증하지 못했습니다."); return; } setPreview(body); }
  function toggleField(drugId: string, field: string) { setSafetyToken(undefined); setSelection((current) => { const fields = new Set(current[drugId] ?? []); if (fields.has(field)) fields.delete(field); else fields.add(field); const next = { ...current, [drugId]: [...fields] }; if (!fields.size) delete next[drugId]; return next; }); }
  function toggleDrug(drug: PreviewDrug) { setSafetyToken(undefined); setSelection((current) => current[drug.id]?.length ? Object.fromEntries(Object.entries(current).filter(([id]) => id !== drug.id)) : { ...current, [drug.id]: drug.fields.map((field) => field.key) }); }
  const selectedCount = Object.keys(selection).length;
  async function safetyBackup() { setError(undefined); setStatus("Pre-restore backup: Generating"); try { const saved = await downloadFullBackup(preRestoreFilename()); if (!saved.size) throw new Error("사전 안전 백업이 비어 있습니다."); const response = await fetch("/api/backup/policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "safety" }) }); const body = await response.json(); if (!response.ok || !body.token) throw new Error("안전 백업 확인 토큰을 만들지 못했습니다."); setSafetyToken(body.token); setStatus("Pre-restore local save initiated"); } catch (caught) { setSafetyToken(undefined); setStatus("Failed"); setError(caught instanceof Error ? caught.message : "사전 안전 백업에 실패했습니다."); } }
  async function restore() { if (!file || !safetyToken || !selectedCount || !window.confirm(`선택한 Data Card ${selectedCount}개의 필드를 백업 상태로 교체할까요?`)) return; setError(undefined); setStatus("Restoring"); const form = new FormData(); form.append("file", file); form.append("safetyToken", safetyToken); form.append("selections", JSON.stringify(Object.entries(selection).map(([drugId, fields]) => ({ drugId, fields })))); const response = await fetch("/api/restore/commit", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "복원에 실패했습니다."); setSafetyToken(undefined); setStatus("Failed"); return; } setResult(`${body.restored}개 Data Card 복원 · 미디어 ${body.mediaRestored}개 복구`); setStatus("Restore complete"); setSafetyToken(undefined); }
  const visible = useMemo(() => preview?.drugs.filter((drug) => drug.koreanName.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())) ?? [], [preview, query]);
  return <>
    <section className="settings-section panel backup-panel" id="backup"><div className="settings-section-heading"><h2>Backup</h2><p>전체 콘텐츠와 실제 이미지 파일을 하나의 로컬 ZIP으로 저장합니다. 인증 비밀은 포함하지 않습니다.</p></div>
      {policy ? <div className="backup-policy-grid"><label><span>Automatic local backup</span><input type="checkbox" checked={policy.enabled} onChange={(event) => setPolicy({ ...policy, enabled: event.target.checked })}/></label><label><span>Frequency</span><select value={policy.frequency} onChange={(event) => setPolicy({ ...policy, frequency: event.target.value as Policy["frequency"] })}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label><span>Scheduled time</span><input type="time" value={policy.time} onChange={(event) => setPolicy({ ...policy, time: event.target.value })}/></label><label><span>Timezone</span><input value={policy.timezone} onChange={(event) => setPolicy({ ...policy, timezone: event.target.value })}/></label><label><span>Missed backup catch-up</span><input type="checkbox" checked={policy.catchUp} onChange={(event) => setPolicy({ ...policy, catchUp: event.target.checked })}/></label></div> : <p className="muted">백업 정책을 불러오는 중…</p>}
      <div className="backup-status-grid"><span>Last local backup<strong>{date(policy?.lastSuccessfulLocalBackupAt)}</strong></span><span>Last attempted<strong>{date(policy?.lastAttemptAt)}</strong></span><span>Next scheduled backup<strong>{date(schedule?.nextAt)}</strong></span><span>Status<strong className={schedule?.overdue ? "overdue" : ""}>{schedule?.overdue ? "Overdue" : "Up to date"}</strong></span></div>
      {error ? <p className="form-error">{error}</p> : null}{status ? <p className="backup-live-status">{status}</p> : null}<div className="backup-actions"><button className="button secondary" onClick={() => void savePolicy()}>정책 저장</button><button className="button" onClick={() => void backupNow()}><Download size={15}/> Back up now</button></div>
    </section>
    <section className="settings-section panel restore-panel" id="restore"><div className="settings-section-heading"><h2>Restore</h2><p>로컬 HerbOverflow 백업에서 선택한 Data Card 또는 필드만 복구합니다.</p></div><label className="button secondary restore-file-button"><FileArchive size={15}/> 백업 파일 선택<input type="file" accept=".zip,application/zip" hidden onChange={(event) => void chooseBackup(event.target.files?.[0])}/></label>
      {preview ? <div className="restore-preview"><header><span><strong>{preview.drugs.length} Data Cards</strong><small>{new Date(preview.manifest.createdAt).toLocaleString("ko-KR")} · media {preview.manifest.media.count}</small></span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="생약 검색"/></header><div className="restore-drug-list">{visible.map((drug) => <article key={drug.id} className={!drug.exists ? "unavailable" : ""}><label><input type="checkbox" disabled={!drug.exists} checked={Boolean(selection[drug.id]?.length)} onChange={() => toggleDrug(drug)}/><strong>{drug.koreanName}</strong><small>{drug.exists ? `${selection[drug.id]?.length ?? 0}/${drug.fields.length} fields` : "현재 DB에 없음"}</small></label>{selection[drug.id]?.length ? <div className="restore-fields">{drug.fields.map((field) => <label key={field.key}><input type="checkbox" checked={selection[drug.id]?.includes(field.key) ?? false} onChange={() => toggleField(drug.id, field.key)}/>{field.label}</label>)}</div> : null}{drug.warnings.map((warning) => <p key={warning}>{warning}</p>)}</article>)}</div><footer><span>{selectedCount}개 Data Card 선택</span>{!safetyToken ? <button className="button secondary" disabled={!selectedCount} onClick={() => void safetyBackup()}><ShieldCheck size={15}/> 사전 안전 백업</button> : <button className="button" onClick={() => void restore()}><RotateCcw size={15}/> 복원 실행</button>}</footer></div> : null}
      {result ? <p className="form-success"><CheckCircle2 size={15}/> {result}</p> : null}
    </section>
  </>;
}

function date(value?: string | null) { return value ? new Date(value).toLocaleString("ko-KR") : "—"; }
function formatBytes(value: number) { return value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`; }
