"use client";
/* eslint-disable @next/next/no-img-element -- private media route cannot use the image optimizer */

import { AlertTriangle, Check, ChevronDown, ChevronLeft, Copy, GripVertical, Heading1, ImagePlus, ListTree, Minus, Plus, Search, Table2, Trash2, Type, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { CollectionBlock, CollectionDocument, CollectionImageBlock, CollectionTableBlock, RichTextValue } from "@/lib/db/schema";
import Link from "next/link";
import { ConceptProvider, conceptTargetAttributes, type ConceptAnchor, type ConceptConnection, type ConceptTarget, useConceptEngine } from "@/components/concept-engine";
import { DrugEditor } from "@/components/drug-editor";
import { SpreadsheetBlock } from "@/components/spreadsheet-block";
import { StudyContentEditor } from "@/components/study-content-editor";
import { useLatexShortcuts } from "@/components/use-latex-shortcuts";
import { applyLatexShortcuts, type LatexShortcut } from "@/lib/latex-shortcuts";

type CollectionData = { id: string; name: string; description: string | null; document: CollectionDocument; revision: number; updatedAt: string | Date };
type DrugResult = { id: string; koreanName: string; latinName: string | null; catalogIndex: number | null; referenceIndex: number | null };
type DrugProfile = Awaited<ReturnType<typeof loadDrug>>;

export function CollectionWorkspace({ initial }: { initial: CollectionData }) {
  const [sourceId, setSourceId] = useState<string>(); const [sourceOpen, setSourceOpen] = useState(false); const [focusAnchor, setFocusAnchor] = useState<string>();
  const navigate = useCallback((anchor: ConceptAnchor) => { if (anchor.ownerType !== "drug") return; setSourceId(anchor.ownerId); setSourceOpen(true); setFocusAnchor(anchor.id); }, []);
  return <ConceptProvider ownerType="collection" ownerId={initial.id} onNavigate={navigate}><WorkspaceBody initial={initial} sourceId={sourceId} setSourceId={setSourceId} sourceOpen={sourceOpen} setSourceOpen={setSourceOpen} focusAnchor={focusAnchor}/></ConceptProvider>;
}

function WorkspaceBody({ initial, sourceId, setSourceId, sourceOpen, setSourceOpen, focusAnchor }: { initial: CollectionData; sourceId?: string; setSourceId: (id?: string) => void; sourceOpen: boolean; setSourceOpen: (value: boolean) => void; focusAnchor?: string }) {
  const [document, setDocument] = useState(initial.document); const [revision, setRevision] = useState(initial.revision); const [name, setName] = useState(initial.name); const [status, setStatus] = useState<"saved" | "dirty" | "saving" | "error">("saved"); const [sourceMode, setSourceMode] = useState(false); const [paneWidth, setPaneWidth] = useState(42); const [conflictsOpen, setConflictsOpen] = useState(false); const timer = useRef<number | undefined>(undefined); const first = useRef(true); const documentRef = useRef(document); const revisionRef = useRef(revision); const saveVersion = useRef(0); const concepts = useConceptEngine(); documentRef.current = document; revisionRef.current = revision;
  useEffect(() => { const stored = Number(localStorage.getItem("collection-source-pane-width")); if (stored >= 25 && stored <= 65) setPaneWidth(stored); }, []);
  useEffect(() => { window.document.body.classList.toggle("source-review-active", sourceMode); return () => window.document.body.classList.remove("source-review-active"); }, [sourceMode]);
  useEffect(() => { if (first.current) { first.current = false; return; } const version = ++saveVersion.current; setStatus("dirty"); window.clearTimeout(timer.current); timer.current = window.setTimeout(async () => { const snapshot = documentRef.current; setStatus("saving"); let response = await saveCollectionDocument(initial.id, snapshot, revisionRef.current); if (response.status === 409) { const current = await fetch(`/api/collections/${initial.id}`).then((result) => result.json()); revisionRef.current = current.revision; response = await saveCollectionDocument(initial.id, documentRef.current, current.revision); } if (response.ok) { const body = await response.json(); revisionRef.current = body.revision; setRevision(body.revision); if (version === saveVersion.current && snapshot === documentRef.current) setStatus("saved"); else setDocument((current) => ({ ...current })); } else setStatus("error"); }, 700); return () => window.clearTimeout(timer.current); }, [document, initial.id]);
  async function rename(value: string) { setName(value); if (value.trim()) await fetch(`/api/collections/${initial.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: value }) }); }
  const unresolved = concepts?.graph.anchors.filter((anchor) => (anchor.status === "broken" || anchor.status === "updated") && concepts.graph.connections.some((edge) => edge.anchorAId === anchor.id ? !edge.historicalA : edge.anchorBId === anchor.id ? !edge.historicalB : false)) ?? [];
  function beginResize(event: React.PointerEvent) { const startX = event.clientX; const start = paneWidth; const move = (pointer: PointerEvent) => { const total = window.innerWidth - 76; const width = Math.max(25, Math.min(65, start + (pointer.clientX - startX) / total * 100)); setPaneWidth(width); }; const end = () => { localStorage.setItem("collection-source-pane-width", String(paneWidth)); window.removeEventListener("pointermove", move); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }
  useEffect(() => { if (!focusAnchor || !sourceOpen) return; const timeout = window.setTimeout(() => window.document.querySelector<HTMLElement>(`.concept-anchor-box.selected, [data-concept-owner-id="${sourceId}"]`)?.scrollIntoView({ block: "center", behavior: "smooth" }), 450); return () => window.clearTimeout(timeout); }, [focusAnchor, sourceId, sourceOpen]);
  return <div className={`collection-workspace ${sourceMode ? "source-review-mode" : ""}`}>
    <header className="collection-workspace-header"><Link href="/collections"><ChevronLeft size={18}/> Collections</Link><input value={name} onChange={(event) => void rename(event.target.value)} aria-label="컬렉션 이름"/><div><label><input type="checkbox" checked={sourceMode} onChange={(event) => setSourceMode(event.target.checked)}/> Source 데이터 카드 보기</label>{unresolved.length ? <button className="conflict-button" onClick={() => setConflictsOpen(true)}><AlertTriangle size={15}/> {unresolved.length}</button> : null}<span className={`save-status ${status}`}><i className="dot"/>{status === "saved" ? "Saved" : status === "saving" ? "Saving" : status === "error" ? "Error" : "Unsaved"}</span></div></header>
    <main className="collection-panes">{sourceOpen ? <><section className="source-pane" style={{ width: `${paneWidth}%` }}><SourcePane selectedId={sourceId} onSelect={setSourceId} onClose={() => setSourceOpen(false)}/></section><button className="pane-divider" onPointerDown={beginResize} aria-label="소스 패널 너비 조절"/></> : <button className="source-pane-reveal" onClick={() => setSourceOpen(true)}>Source 열기</button>}<section className="collection-document-pane"><CollectionBlockEditor collectionId={initial.id} document={document} onChange={setDocument}/></section></main>
    {conflictsOpen ? <ConflictDialog anchors={unresolved} allAnchors={concepts?.graph.anchors ?? []} connections={concepts?.graph.connections ?? []} onClose={() => setConflictsOpen(false)} onReload={() => concepts?.reload()}/> : null}
  </div>;
}

function SourcePane({ selectedId, onSelect, onClose }: { selectedId?: string; onSelect: (id?: string) => void; onClose: () => void }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<DrugResult[]>([]); const [profile, setProfile] = useState<DrugProfile>();
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => fetch(`/api/drugs/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then((response) => response.json()).then(setResults).catch(() => undefined), 180); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query]);
  useEffect(() => { if (!selectedId) { setProfile(undefined); return; } void loadDrug(selectedId).then(setProfile); }, [selectedId]);
  return <div className="source-pane-inner"><header><strong>Source</strong><button onClick={onClose} aria-label="소스 패널 닫기"><X size={17}/></button></header><div className="source-search"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="생약명, Latin name, 번호 검색"/>{query || !selectedId ? <div className="source-results">{results.map((drug) => <button key={drug.id} onClick={() => { onSelect(drug.id); setQuery(""); }}><strong>{drug.koreanName}</strong><span>{drug.latinName || "Latin name 없음"}</span><small>{drug.catalogIndex ?? drug.referenceIndex ?? "—"}</small></button>)}</div> : null}</div>{profile ? <div className="embedded-drug"><DrugEditor modal id={profile.id} family={profile.family} relatedDrugs={profile.relatedDrugs} similarDrugs={profile.similarDrugs} availableDrugs={profile.availableDrugs} initial={{ koreanName: profile.koreanName, latinName: profile.latinName, origin: profile.origin, origins: profile.origins, scientificName: profile.scientificName, medicinalPart: profile.medicinalPart, familyId: profile.familyId, importance: profile.importance, sections: profile.sections }}/></div> : <div className="source-empty">검색 결과에서 Data Card를 선택하세요.</div>}</div>;
}

async function loadDrug(id: string) { const response = await fetch(`/api/drugs/${id}`); if (!response.ok) throw new Error("Source load failed"); return response.json() as Promise<{ id: string; family: string | null; koreanName: string; latinName: string | null; origin: string | null; origins: { nameKo: string | null; scientificName: string | null }[]; scientificName: string | null; medicinalPart: string | null; familyId: string | null; importance: "중요" | "중간" | "비중요"; sections: import("@/lib/db/schema").StudySection[]; relatedDrugs: never[]; similarDrugs: never[]; availableDrugs: never[] }>; }
function saveCollectionDocument(id: string, document: CollectionDocument, revision: number) { return fetch(`/api/collections/${id}/document`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ document, revision }) }); }

function CollectionBlockEditor({ collectionId, document, onChange }: { collectionId: string; document: CollectionDocument; onChange: (document: CollectionDocument) => void }) {
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [dragging, setDragging] = useState<string[]>(); const [dropIndex, setDropIndex] = useState<number>(); const [listMenuOpen, setListMenuOpen] = useState(false); const [listMode, setListMode] = useState<"hierarchy4" | "hierarchy3">("hierarchy4"); const blocks = document.blocks; const concepts = useConceptEngine();
  const commit = (next: CollectionBlock[]) => onChange({ version: 1, blocks: next });
  function add(type: CollectionBlock["type"], index = blocks.length, hierarchyMode: "hierarchy4" | "hierarchy3" = listMode) { const block = newBlock(type, hierarchyMode); commit([...blocks.slice(0, index), block, ...blocks.slice(index)]); requestAnimationFrame(() => window.document.querySelector<HTMLElement>(`[data-block-id="${block.id}"] [contenteditable]`)?.focus()); }
  function update(id: string, next: CollectionBlock) { commit(blocks.map((block) => block.id === id ? next : block)); }
  async function remove(ids = selected) { const targets = ids.size ? ids : new Set<string>(); if (!targets.size) return; if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [...targets] }) === false) return; commit(blocks.filter((block) => !targets.has(block.id))); setSelected(new Set()); }
  function choose(id: string, event: React.MouseEvent) { if (event.metaKey || event.ctrlKey) setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); else if (event.shiftKey && selected.size) { const indexes = [...selected].map((value) => blocks.findIndex((block) => block.id === value)); const from = Math.min(...indexes, blocks.findIndex((block) => block.id === id)); const to = Math.max(...indexes, blocks.findIndex((block) => block.id === id)); setSelected(new Set(blocks.slice(from, to + 1).map((block) => block.id))); } else setSelected(new Set([id])); }
  function drop(index: number) { if (!dragging?.length) return; const moving = blocks.filter((block) => dragging.includes(block.id)); const rest = blocks.filter((block) => !dragging.includes(block.id)); const beforeCount = blocks.slice(0, index).filter((block) => !dragging.includes(block.id)).length; commit([...rest.slice(0, beforeCount), ...moving, ...rest.slice(beforeCount)]); setDragging(undefined); setDropIndex(undefined); }
  return <div className="collection-editor"><div className="block-command-bar"><span>블록 추가</span><button onClick={() => add("text")}><Type size={14}/> 텍스트</button><button onClick={() => add("heading")}><Heading1 size={14}/> 제목</button><div className="block-split-wrap"><div className="block-split-button"><button onClick={() => add("hierarchy", blocks.length, listMode)}><ListTree size={14}/> 번호 리스트</button><button className="block-split-toggle" onClick={() => setListMenuOpen((value) => !value)} aria-label="번호 리스트 형식 선택" aria-expanded={listMenuOpen}><ChevronDown size={13}/></button></div>{listMenuOpen ? <div className="block-split-menu"><button onClick={() => { setListMode("hierarchy4"); setListMenuOpen(false); add("hierarchy", blocks.length, "hierarchy4"); }}><strong>4단계 번호 리스트</strong><small>i) → ① → a) → •</small></button><button onClick={() => { setListMode("hierarchy3"); setListMenuOpen(false); add("hierarchy", blocks.length, "hierarchy3"); }}><strong>3단계 번호 리스트</strong><small>① → a) → •</small></button></div> : null}</div><button onClick={() => add("image")}><ImagePlus size={14}/> 이미지</button><button onClick={() => add("table")}><Table2 size={14}/> 표</button>{selected.size ? <><button onClick={() => { const copies = blocks.filter((block) => selected.has(block.id)).map(duplicateBlock); commit([...blocks, ...copies]); }}><Copy size={14}/> 복제</button><button onClick={() => void remove()}><Trash2 size={14}/> {selected.size}개 삭제</button></> : null}</div>
    <div className="collection-block-list">{blocks.length ? blocks.map((block, index) => <div key={block.id}><div className={`block-drop-line ${dropIndex === index ? "active" : ""}`} onDragOver={(event) => { event.preventDefault(); setDropIndex(index); }} onDrop={(event) => { event.preventDefault(); drop(index); }}/><article data-block-id={block.id} className={`collection-block ${selected.has(block.id) ? "selected" : ""}`}><aside><button className="block-drag-handle" draggable onClick={(event) => choose(block.id, event)} onDragStart={(event) => { const ids = selected.has(block.id) ? [...selected] : [block.id]; setDragging(ids); event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("application/x-herb-block-ids", ids.join(",")); }} onDragEnd={() => { setDragging(undefined); setDropIndex(undefined); }} aria-label="블록 선택 및 이동"><GripVertical size={16}/></button><button className="block-add-control" onClick={() => add("text", index + 1)} aria-label="아래에 텍스트 블록 추가"><Plus size={14}/></button><button className="block-remove-control" onClick={() => void remove(new Set([block.id]))} aria-label="현재 블록 삭제"><Minus size={14}/></button></aside><BlockContent collectionId={collectionId} block={block} onChange={(next) => update(block.id, next)} onEnter={() => add(block.type === "heading" ? "text" : block.type, index + 1, block.type === "hierarchy" ? block.mode ?? "hierarchy4" : listMode)} onRemove={() => void remove(new Set([block.id]))}/></article></div>) : <button className="collection-empty-document" onClick={() => add("text")}><Plus/> 첫 블록 추가</button>}<div className={`block-drop-line ${dropIndex === blocks.length ? "active" : ""}`} onDragOver={(event) => { event.preventDefault(); setDropIndex(blocks.length); }} onDrop={(event) => { event.preventDefault(); drop(blocks.length); }}/></div>
  </div>;
}

function BlockContent({ collectionId, block, onChange, onEnter, onRemove }: { collectionId: string; block: CollectionBlock; onChange: (block: CollectionBlock) => void; onEnter: () => void; onRemove: () => void }) {
  if (block.type === "text" || block.type === "heading") { const target: ConceptTarget = { ownerType: "collection", ownerId: collectionId, targetType: block.type === "text" ? "collection_text" : "collection_heading", targetRef: { blockId: block.id } }; return <div className="collection-text-block">{block.type === "heading" ? <select value={block.level} onChange={(event) => onChange({ ...block, level: Number(event.target.value) as 1 | 2 | 3 })} aria-label="제목 단계"><option value="1">H1</option><option value="2">H2</option><option value="3">H3</option></select> : null}<RichBlockEditor value={block.content} target={target} heading={block.type === "heading" ? block.level : undefined} onChange={(content) => onChange({ ...block, content })} onEnter={onEnter} onEmptyBackspace={onRemove}/></div>; }
  if (block.type === "hierarchy") return <StudyContentEditor items={block.items} blocks={block.blocks} mode={block.mode ?? "hierarchy4"} concept={{ ownerType: "collection", ownerId: collectionId, blockId: block.id }} onChange={(value) => onChange({ ...block, ...value })}/>;
  if (block.type === "image") return <CollectionImage block={block} collectionId={collectionId} onChange={(next) => onChange(next)}/>;
  return <SpreadsheetBlock block={block} collectionId={collectionId} onChange={(next) => onChange(next)}/>;
}

function RichBlockEditor({ value, target, heading, onChange, onEnter, onEmptyBackspace }: { value: RichTextValue; target: ConceptTarget; heading?: 1 | 2 | 3; onChange: (value: RichTextValue) => void; onEnter: () => void; onEmptyBackspace: () => void }) {
  const editor = useRef<HTMLDivElement>(null); const composing = useRef(false); const concepts = useConceptEngine(); const shortcuts = useLatexShortcuts(); useEffect(() => { const node = editor.current; if (node && document.activeElement !== node && node.innerHTML !== (value.html || escapeHtml(value.text))) node.innerHTML = value.html || escapeHtml(value.text); }, [value]);
  function emit(includeEnd = false) { const node = editor.current; if (!node) return; normalizeRichText(node, shortcuts, includeEnd); const next = { text: node.innerText.replace(/\n$/, ""), html: node.innerHTML }; if (concepts?.reconcileText(target, value.text, next.text) === false) { node.innerHTML = value.html || escapeHtml(value.text); return; } onChange(next); }
  return <div className={`collection-rich-block ${heading ? `heading-${heading}` : ""}`}><div className="rich-block-toolbar"><button onMouseDown={(event) => event.preventDefault()} onClick={() => document.execCommand("bold")}><b>B</b></button><button onMouseDown={(event) => event.preventDefault()} onClick={() => document.execCommand("italic")}><i>I</i></button><button onMouseDown={(event) => event.preventDefault()} onClick={() => document.execCommand("hiliteColor", false, "#594f24")}>Highlight</button><label><input type="color" onChange={(event) => document.execCommand("foreColor", false, event.target.value)}/></label></div><div ref={editor} {...conceptTargetAttributes(target)} contentEditable suppressContentEditableWarning data-placeholder={heading ? `Heading ${heading}` : "내용을 입력하세요"} onDragOver={(event) => { if (event.dataTransfer.types.includes("application/x-herb-block-ids")) event.preventDefault(); }} onDrop={(event) => { if (event.dataTransfer.types.includes("application/x-herb-block-ids")) { event.preventDefault(); event.stopPropagation(); } }} onCompositionStart={() => { composing.current = true; }} onCompositionEnd={() => { composing.current = false; emit(); }} onInput={() => { if (!composing.current) emit(); }} onBlur={() => emit(true)} onContextMenu={(event) => concepts?.openMenu(event, target)} onKeyDown={(event) => { if (event.nativeEvent.isComposing || composing.current) return; if ((event.metaKey || event.ctrlKey) && ["b", "i"].includes(event.key.toLowerCase())) { event.preventDefault(); document.execCommand(event.key.toLowerCase() === "b" ? "bold" : "italic"); emit(); } else if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); emit(true); onEnter(); } else if (event.key === "Backspace" && !editor.current?.innerText) { event.preventDefault(); onEmptyBackspace(); } }}/></div>;
}

function CollectionImage({ block, collectionId, onChange }: { block: CollectionImageBlock; collectionId: string; onChange: (block: CollectionImageBlock) => void }) { const input = useRef<HTMLInputElement>(null); const concepts = useConceptEngine(); const target: ConceptTarget = { ownerType: "collection", ownerId: collectionId, targetType: "image", targetRef: { blockId: block.id, mediaAssetId: block.mediaAssetId || undefined } }; async function upload(file?: File) { if (!file?.type.startsWith("image/")) return; const bitmap = await createImageBitmap(file); const form = new FormData(); form.append("file", file); form.append("width", String(bitmap.width)); form.append("height", String(bitmap.height)); bitmap.close(); const response = await fetch("/api/media", { method: "POST", body: form }); if (response.ok) { const asset = await response.json(); onChange({ ...block, mediaAssetId: asset.id }); } } if (!block.mediaAssetId) return <div className="collection-image-drop" tabIndex={0} onClick={() => input.current?.click()} onPaste={(event) => void upload([...event.clipboardData.items].find((item) => item.type.startsWith("image/"))?.getAsFile() ?? undefined)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void upload([...event.dataTransfer.files][0]); }}><ImagePlus/> 이미지 업로드 · 붙여넣기 · 드롭<input ref={input} hidden type="file" accept="image/*" onChange={(event) => void upload(event.target.files?.[0])}/></div>; return <figure {...conceptTargetAttributes(target)} className={`collection-image-block ${block.align}`} style={{ width: `${block.widthPercent}%` }} onContextMenu={(event) => concepts?.openMenu(event, target, undefined, block.mediaAssetId)}><img src={`/api/media/${block.mediaAssetId}/content`} alt="컬렉션 이미지"/><input type="range" min="15" max="100" value={block.widthPercent} onChange={(event) => onChange({ ...block, widthPercent: Number(event.target.value) })}/><span>{(["left", "center", "right"] as const).map((align) => <button className={block.align === align ? "active" : ""} key={align} onClick={() => onChange({ ...block, align })}>{align}</button>)}</span></figure>; }

function ConflictDialog({ anchors, allAnchors, connections, onClose, onReload }: { anchors: ConceptAnchor[]; allAnchors: ConceptAnchor[]; connections: ConceptConnection[]; onClose: () => void; onReload: () => void }) { async function action(connection: ConceptConnection, anchor: ConceptAnchor, value: "accept" | "historical" | "remove" | "reassign") { if (value === "remove") await fetch(`/api/concept-connections/${connection.id}`, { method: "DELETE" }); else { const side = connection.anchorAId === anchor.id ? "a" : "b"; let replacementAnchorId: string | undefined; if (value === "reassign") { const candidates = allAnchors.filter((candidate) => candidate.id !== anchor.id && candidate.status !== "broken"); const choice = Number(window.prompt(`재지정할 앵커를 선택하세요:\n${candidates.map((candidate, index) => `${index + 1}. ${candidate.snapshotText || candidate.targetType}`).join("\n")}`, "1")); replacementAnchorId = candidates[choice - 1]?.id; if (!replacementAnchorId) return; } await fetch(`/api/concept-connections/${connection.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: `${value}-${side}`, replacementAnchorId }) }); } await onReload(); } return <div className="conflict-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="conflict-dialog"><header><div><h2>연결 충돌</h2><p>변경되거나 누락된 개념 끝점을 검토하세요.</p></div><button onClick={onClose}><X/></button></header>{anchors.map((anchor) => { const edges = connections.filter((edge) => edge.anchorAId === anchor.id || edge.anchorBId === anchor.id); return <article key={anchor.id}><AlertTriangle/><div><strong>{anchor.status === "broken" ? "누락된 끝점" : "업데이트된 원본"}</strong><p>{anchor.snapshotText || anchor.targetType}</p>{edges.map((edge) => <span key={edge.id}>{anchor.status === "updated" ? <button onClick={() => void action(edge, anchor, "accept")}><Check size={13}/> 현재 내용 수락</button> : null}<button onClick={() => void action(edge, anchor, "reassign")}>새 앵커로 재지정</button><button onClick={() => void action(edge, anchor, "historical")}>기록으로 유지</button><button onClick={() => void action(edge, anchor, "remove")}>연결 삭제</button></span>)}</div></article>; })}<footer><small>기록으로 유지하면 기존 스냅샷은 보존되고 라이브 끝점으로 취급되지 않습니다.</small></footer></section></div>; }

function newBlock(type: CollectionBlock["type"], hierarchyMode: "hierarchy4" | "hierarchy3" = "hierarchy4"): CollectionBlock { const id = crypto.randomUUID(); if (type === "heading") return { id, type, level: 2, content: { text: "" } }; if (type === "text") return { id, type, content: { text: "" } }; if (type === "hierarchy") return { id, type, mode: hierarchyMode, items: [] }; if (type === "image") return { id, type, mediaAssetId: "", widthPercent: 50, align: "center" }; const cells: CollectionTableBlock["cells"] = {}; for (let row = 0; row < 5; row++) for (let column = 0; column < 5; column++) cells[`${row}:${column}`] = { id: crypto.randomUUID(), text: "" }; return { id, type: "table", rows: 5, columns: 5, cells, rowSizes: Array(5).fill(34), columnSizes: Array(5).fill(128), mergedRanges: [] }; }
function duplicateBlock(source: CollectionBlock): CollectionBlock { const block = structuredClone(source); block.id = crypto.randomUUID(); if (block.type === "table") for (const cell of Object.values(block.cells)) cell.id = crypto.randomUUID(); if (block.type === "hierarchy") { const refreshItems = (items: import("@/lib/db/schema").StudyItem[]): import("@/lib/db/schema").StudyItem[] => items.map((item) => ({ ...item, id: crypto.randomUUID(), children: item.children ? refreshItems(item.children) : undefined })); block.blocks = block.blocks?.map((nested) => nested.type === "items" ? { ...nested, id: crypto.randomUUID(), items: refreshItems(nested.items) } : { ...nested, id: crypto.randomUUID() }); block.items = block.blocks?.flatMap((nested) => nested.type === "items" ? nested.items : []) ?? refreshItems(block.items); } return block; }
function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function normalizeRichText(root: HTMLElement, shortcuts: LatexShortcut[], includeEnd: boolean) { const selection = window.getSelection(); const active = Boolean(selection?.rangeCount && selection.isCollapsed && root.contains(selection.anchorNode)); const offset = active ? richCaretOffset(root) : 0; const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let delta = 0; while (walker.nextNode()) { const node = walker.currentNode as Text; const before = node.data; const after = applyLatexShortcuts(before, includeEnd, shortcuts); if (before !== after) { node.data = after; delta += after.length - before.length; } } if (active && delta) placeRichCaret(root, Math.max(0, offset + delta)); }
function richCaretOffset(root: HTMLElement) { const selection = window.getSelection(); if (!selection?.rangeCount) return 0; const range = selection.getRangeAt(0).cloneRange(); range.selectNodeContents(root); range.setEnd(selection.anchorNode!, selection.anchorOffset); return range.toString().length; }
function placeRichCaret(root: HTMLElement, offset: number) { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let remaining = offset; while (walker.nextNode()) { const node = walker.currentNode as Text; if (remaining <= node.length) { const range = document.createRange(); range.setStart(node, remaining); range.collapse(true); const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(range); return; } remaining -= node.length; } }
