"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { CONNECTION_PALETTE } from "@/lib/concept-connection-colors";
import { serializeConceptAnchorTargetRef } from "@/lib/concept-target-ref";
import type { ConceptAnchorStatus, ConceptAnchorTargetRef, ConceptOwnerType, ConceptTargetType } from "@/lib/db/schema";

export type ConceptAnchor = { id: string; ownerType: ConceptOwnerType; ownerId: string; targetType: ConceptTargetType; targetRef: ConceptAnchorTargetRef; startOffset: number | null; endOffset: number | null; status: ConceptAnchorStatus; snapshotText: string | null; snapshotHash: string | null; assetVersion: string | null };
export type ConceptConnection = { id: string; anchorAId: string; anchorBId: string; color: string; anchorASnapshot: { text?: string; hash?: string; assetVersion?: string }; anchorBSnapshot: { text?: string; hash?: string; assetVersion?: string }; historicalA: boolean; historicalB: boolean };
export type ConceptTarget = { ownerType: ConceptOwnerType; ownerId: string; targetType: ConceptTargetType; targetRef: ConceptAnchorTargetRef };
type Graph = { anchors: ConceptAnchor[]; connections: ConceptConnection[] };
type MenuState = { x: number; y: number; target: ConceptTarget; startOffset: number | null; endOffset: number | null; text: string; assetVersion?: string };
type ConnectionMenuState = { x: number; y: number; connectionId: string };
type RectState = { anchor: ConceptAnchor; rect: DOMRect; union: DOMRect; field: DOMRect | null; contentLeft: number | null };
type BreakQuery = { ownerId: string; blockIds?: string[]; sectionIds?: string[]; itemIds?: string[]; cellIds?: string[] };
type ConceptContextValue = { graph: Graph; reload: () => Promise<void>; openMenu: (event: React.MouseEvent<HTMLElement>, target: ConceptTarget, wholeText?: string, assetVersion?: string) => boolean; createSelectionAnchor: (target: ConceptTarget, node: HTMLElement, assetVersion?: string) => Promise<boolean>; reconcileText: (target: ConceptTarget, before: string, after: string) => boolean; breakTarget: (target: ConceptTarget) => Promise<boolean>; breakAnchors: (query: BreakQuery) => Promise<boolean>; selectAnchor: (id?: string) => void };

const ConceptContext = createContext<ConceptContextValue | null>(null);
const targetKey = (target: ConceptTarget | ConceptAnchor) => `${target.ownerType}:${target.ownerId}:${target.targetType}:${serializeConceptAnchorTargetRef(target.targetRef)}`;
const sameTarget = (anchor: ConceptAnchor, target: ConceptTarget) => targetKey(anchor) === targetKey(target);

export function useConceptEngine() { return useContext(ConceptContext); }
export function conceptTargetAttributes(target: ConceptTarget) { return { "data-concept-owner-type": target.ownerType, "data-concept-owner-id": target.ownerId, "data-concept-target-type": target.targetType, "data-concept-target-ref": serializeConceptAnchorTargetRef(target.targetRef) } as const; }

export function ConceptBoundary({ ownerType, ownerId, children, onNavigate }: { ownerType: ConceptOwnerType; ownerId: string; children: React.ReactNode; onNavigate?: (anchor: ConceptAnchor, connection: ConceptConnection) => void }) {
  const existing = useConceptEngine();
  return existing ? children : <ConceptProvider ownerType={ownerType} ownerId={ownerId} onNavigate={onNavigate}>{children}</ConceptProvider>;
}

export function ConceptProvider({ ownerType, ownerId, children, onNavigate }: { ownerType: ConceptOwnerType; ownerId: string; children: React.ReactNode; onNavigate?: (anchor: ConceptAnchor, connection: ConceptConnection) => void }) {
  const [graph, setGraph] = useState<Graph>({ anchors: [], connections: [] }); const [menu, setMenu] = useState<MenuState>(); const [connectionMenu, setConnectionMenu] = useState<ConnectionMenuState>(); const [rects, setRects] = useState<RectState[]>([]); const [hovered, setHovered] = useState<string>(); const [selected, setSelected] = useState<string>(); const [dragFrom, setDragFrom] = useState<string>(); const [pointer, setPointer] = useState<{ x: number; y: number }>(); const [snapTarget, setSnapTarget] = useState<string>(); const graphRef = useRef(graph); const snapTargetRef = useRef<string | undefined>(undefined); graphRef.current = graph;
  const reload = useCallback(async () => { const response = await fetch(`/api/concept-anchors?ownerType=${ownerType}&ownerId=${ownerId}`); if (response.ok) setGraph(await response.json()); }, [ownerId, ownerType]);
  useEffect(() => { void reload(); }, [reload]);

  const calculate = useCallback(() => {
    const next: RectState[] = [];
    for (const anchor of graphRef.current.anchors) {
      const selector = `[data-concept-owner-type="${anchor.ownerType}"][data-concept-owner-id="${anchor.ownerId}"][data-concept-target-type="${anchor.targetType}"]`;
      const serializedTargetRef = serializeConceptAnchorTargetRef(anchor.targetRef);
      const nodes = [...document.querySelectorAll<HTMLElement>(selector)]; const node = nodes.find((candidate) => candidate.dataset.conceptTargetRef === serializedTargetRef); if (!node) continue;
      const clientRects = anchor.startOffset != null && anchor.endOffset != null ? textRangeRects(node, anchor.startOffset, anchor.endOffset) : [node.getBoundingClientRect()];
      const visible = clientRects.filter((rect) => rect.width > 0 && rect.height > 0); if (!visible.length) continue;
      const union = unionRects(visible); const fieldElement = node.closest<HTMLElement>(".profile-field"); const field = fieldElement?.getBoundingClientRect() ?? null; const contentBounds = fieldElement ? [fieldElement, ...fieldElement.querySelectorAll<HTMLElement>(".hierarchy-marker, .hierarchy-row, .rich-study-input, input, textarea, [contenteditable='true']")].map((element) => element.getBoundingClientRect()).filter((bounds) => bounds.width > 0 || bounds.height > 0) : []; const contentLeft = contentBounds.length ? Math.min(...contentBounds.map((bounds) => bounds.left)) : null; for (const rect of visible) next.push({ anchor, rect, union, field, contentLeft });
    }
    setRects(next);
  }, []);
  useEffect(() => { calculate(); const observer = new ResizeObserver(calculate); observer.observe(document.body); const handler = () => calculate(); window.addEventListener("scroll", handler, true); window.addEventListener("resize", handler); return () => { observer.disconnect(); window.removeEventListener("scroll", handler, true); window.removeEventListener("resize", handler); }; }, [calculate, graph]);
  useEffect(() => { const move = (event: PointerEvent) => { if (dragFrom) return; const eventElement = event.target instanceof Element ? event.target : undefined; const connectionId = eventElement?.closest<SVGPathElement>("[data-concept-connection-id]")?.dataset.conceptConnectionId; if (connectionId) { setHovered(connectionId); return; } const controlAnchorId = eventElement?.closest<HTMLElement>("[data-concept-anchor-id]")?.dataset.conceptAnchorId; if (controlAnchorId) { setHovered(controlAnchorId); return; } const hit = uniqueRects(rects).find((item) => pointIn(event.clientX, event.clientY, item.union)); setHovered(hit?.anchor.id); }; window.addEventListener("pointermove", move); return () => window.removeEventListener("pointermove", move); }, [dragFrom, rects]);

  const openMenu = useCallback((event: React.MouseEvent<HTMLElement>, target: ConceptTarget, wholeText?: string, assetVersion?: string) => {
    const node = event.currentTarget; const range = selectedOffsets(node); const text = range ? range.text : wholeText;
    if (!text && !assetVersion) return false; event.preventDefault(); setMenu({ x: event.clientX, y: event.clientY, target, startOffset: range?.start ?? null, endOffset: range?.end ?? null, text: text ?? "", assetVersion }); return true;
  }, []);
  const persistAnchor = useCallback(async (value: Omit<MenuState, "x" | "y">) => { const response = await fetch("/api/concept-anchors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...value.target, startOffset: value.startOffset, endOffset: value.endOffset, snapshotText: value.text || undefined, assetVersion: value.assetVersion }) }); if (!response.ok) { const responseBody = await response.text(); console.error("Failed to create concept anchor", { status: response.status, statusText: response.statusText, responseBody }); return false; } const anchor = await response.json(); setSelected(anchor.id); setGraph((current) => ({ ...current, anchors: current.anchors.some((item) => item.id === anchor.id) ? current.anchors : [...current.anchors, anchor] })); return true; }, []);
  async function createAnchor() { if (!menu) return; const value = menu; setMenu(undefined); await persistAnchor(value); }
  const createSelectionAnchor = useCallback(async (target: ConceptTarget, node: HTMLElement, assetVersion?: string) => { const range = selectedOffsets(node); if (!range && !assetVersion) return false; return persistAnchor({ target, startOffset: range?.start ?? null, endOffset: range?.end ?? null, text: range?.text ?? "", assetVersion }); }, [persistAnchor]);

  const reconcileText = useCallback((target: ConceptTarget, before: string, after: string) => {
    if (before === after) return true; const edit = textEdit(before, after); const affected = graphRef.current.anchors.filter((anchor) => sameTarget(anchor, target) && anchor.startOffset != null && anchor.endOffset != null && anchor.status !== "broken");
    const changes = affected.map((anchor) => ({ anchor, adjusted: adjustAnchorRange(anchor.startOffset!, anchor.endOffset!, edit.start, edit.oldEnd, edit.inserted.length) }));
    if (changes.some(({ adjusted }) => adjusted.end <= adjusted.start) && !window.confirm("연결된 개념 관계가 이 앵커에 의존합니다. 마지막 앵커 내용을 삭제하면 연결은 유지되지만 끝점이 누락 상태가 됩니다. 계속할까요?")) return false;
    for (const { anchor, adjusted } of changes) {
      const vanished = adjusted.end <= adjusted.start;
      const snapshotText = vanished ? anchor.snapshotText : after.slice(adjusted.start, adjusted.end);
      const changedFromResolution = graphRef.current.connections.some((edge) => edge.anchorAId === anchor.id ? !edge.historicalA && edge.anchorASnapshot.text !== snapshotText : edge.anchorBId === anchor.id ? !edge.historicalB && edge.anchorBSnapshot.text !== snapshotText : false);
      const patch = vanished ? { status: "broken" } : { startOffset: adjusted.start, endOffset: adjusted.end, snapshotText, status: changedFromResolution ? "updated" : "healthy" };
      setGraph((current) => ({ ...current, anchors: current.anchors.map((item) => item.id === anchor.id ? { ...item, ...patch } as ConceptAnchor : item) }));
      void fetch(`/api/concept-anchors/${anchor.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) });
    }
    return true;
  }, []);
  const breakAnchors = useCallback(async (query: BreakQuery) => { const matches = graphRef.current.anchors.filter((anchor) => anchor.ownerId === query.ownerId && anchor.status !== "broken" && (!query.blockIds || query.blockIds.includes(anchor.targetRef.blockId ?? "")) && (!query.sectionIds || query.sectionIds.includes(anchor.targetRef.sectionId ?? "")) && (!query.itemIds || query.itemIds.includes(anchor.targetRef.itemId ?? "")) && (!query.cellIds || query.cellIds.includes(anchor.targetRef.cellId ?? ""))); if (matches.length && !window.confirm("이 콘텐츠에 연결된 개념 관계가 있습니다. 삭제 후에도 연결 기록은 남고 누락 상태로 표시됩니다. 계속할까요?")) return false; await Promise.all(matches.map((anchor) => fetch(`/api/concept-anchors/${anchor.id}`, { method: "DELETE" }))); if (matches.length) await reload(); return true; }, [reload]);
  const breakTarget = useCallback(async (target: ConceptTarget) => { const matches = graphRef.current.anchors.filter((anchor) => sameTarget(anchor, target) && anchor.status !== "broken"); if (matches.length && !window.confirm("이 콘텐츠에 연결된 개념 관계가 있습니다. 삭제 후에도 연결 기록은 남고 누락 상태로 표시됩니다. 계속할까요?")) return false; await Promise.all(matches.map((anchor) => fetch(`/api/concept-anchors/${anchor.id}`, { method: "DELETE" }))); if (matches.length) await reload(); return true; }, [reload]);

  const clearConnectionDrag = useCallback(() => { setDragFrom(undefined); setPointer(undefined); setSnapTarget(undefined); snapTargetRef.current = undefined; }, []);
  const connect = useCallback(async (fromId: string, toId: string) => { if (fromId === toId) return; clearConnectionDrag(); const response = await fetch("/api/concept-connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ anchorAId: fromId, anchorBId: toId }) }); if (response.ok) { const edge = await response.json(); setSelected(edge.id); await reload(); } }, [clearConnectionDrag, reload]);
  const deleteConnection = useCallback(async (connectionId: string) => { const response = await fetch(`/api/concept-connections/${connectionId}`, { method: "DELETE" }); if (!response.ok) { console.error("Failed to delete concept connection", { connectionId, status: response.status, responseBody: await response.text() }); return; } setGraph((current) => ({ ...current, connections: current.connections.filter((edge) => edge.id !== connectionId) })); setConnectionMenu(undefined); setSelected((current) => current === connectionId ? undefined : current); setHovered((current) => current === connectionId ? undefined : current); }, []);
  const updateConnectionColor = useCallback(async (connectionId: string, color: string) => { const response = await fetch(`/api/concept-connections/${connectionId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ color }) }); if (!response.ok) { console.error("Failed to update concept connection color", { connectionId, color, status: response.status, responseBody: await response.text() }); return; } const updated: ConceptConnection = await response.json(); setGraph((current) => ({ ...current, connections: current.connections.map((edge) => edge.id === connectionId ? { ...edge, color: updated.color } : edge) })); }, []);
  const navigateTo = useCallback((anchor: ConceptAnchor, edge: ConceptConnection) => { const serializedTargetRef = serializeConceptAnchorTargetRef(anchor.targetRef); const target = [...document.querySelectorAll<HTMLElement>(`[data-concept-owner-id="${anchor.ownerId}"][data-concept-target-ref]`)].find((node) => node.dataset.conceptTargetRef === serializedTargetRef); if (target) { target.scrollIntoView({ block: "center", behavior: "smooth" }); target.focus({ preventScroll: true }); } else onNavigate?.(anchor, edge); }, [onNavigate]);
  useEffect(() => { if (!dragFrom) return; const anchors = uniqueRects(rects); const move = (event: PointerEvent) => { setPointer({ x: event.clientX, y: event.clientY }); const target = nearestSnapTarget(anchors, event.clientX, event.clientY, dragFrom); const targetId = target?.anchor.id; snapTargetRef.current = targetId; setSnapTarget(targetId); }; const up = () => { const targetId = snapTargetRef.current; if (targetId) void connect(dragFrom, targetId); else clearConnectionDrag(); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, [clearConnectionDrag, connect, dragFrom, rects]);
  useEffect(() => { const dismiss = (event: MouseEvent) => { setMenu(undefined); setConnectionMenu(undefined); if (isEditableTarget(event.target)) setSelected(undefined); }; const key = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenu(undefined); setConnectionMenu(undefined); setSelected(undefined); clearConnectionDrag(); return; } if ((event.key === "Delete" || event.key === "Backspace") && selected && graphRef.current.connections.some((edge) => edge.id === selected)) { event.preventDefault(); void deleteConnection(selected); } }; window.addEventListener("mousedown", dismiss); window.addEventListener("keydown", key); return () => { window.removeEventListener("mousedown", dismiss); window.removeEventListener("keydown", key); }; }, [clearConnectionDrag, deleteConnection, selected]);

  const value = useMemo<ConceptContextValue>(() => ({ graph, reload, openMenu, createSelectionAnchor, reconcileText, breakTarget, breakAnchors, selectAnchor: setSelected }), [breakAnchors, breakTarget, createSelectionAnchor, graph, openMenu, reconcileText, reload]);
  const anchors = uniqueRects(rects); const sortedConnections = [...graph.connections].sort((left, right) => left.id.localeCompare(right.id)); const menuConnection = connectionMenu ? graph.connections.find((edge) => edge.id === connectionMenu.connectionId) : undefined;
  return <ConceptContext.Provider value={value}>{children}{typeof document !== "undefined" ? createPortal(<div className="concept-overlay" aria-hidden={!dragFrom}>
    <svg className="concept-lines">{sortedConnections.map((edge) => { const a = anchors.find((item) => item.anchor.id === edge.anchorAId); const b = anchors.find((item) => item.anchor.id === edge.anchorBId); if (!a && !b) return null; const path = connectionPath(a, b, edge, sortedConnections); const state = selected === edge.id ? "selected" : hovered === edge.id ? "hovered" : hovered === edge.anchorAId || hovered === edge.anchorBId ? "related" : "normal"; const selectConnection = () => { setSelected(edge.id); const mountedId = a ? edge.anchorAId : edge.anchorBId; const otherId = mountedId === edge.anchorAId ? edge.anchorBId : edge.anchorAId; const other = graph.anchors.find((anchor) => anchor.id === otherId); if (other) navigateTo(other, edge); }; return <g key={edge.id} className={`concept-line-group ${state}`}><path d={path} className="concept-line-hit" data-concept-connection-id={edge.id} onPointerEnter={() => setHovered(edge.id)} onPointerLeave={() => setHovered(undefined)} onClick={selectConnection} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); setSelected(edge.id); setConnectionMenu({ x: event.clientX, y: event.clientY, connectionId: edge.id }); }}/><path d={path} stroke={edge.color} className="concept-line-visible"/></g>; })}{dragFrom && pointer ? (() => { const from = anchors.find((item) => item.anchor.id === dragFrom); const target = anchors.find((item) => item.anchor.id === snapTarget); if (!from) return null; const path = target ? connectionPath(from, target) : orthogonalPath(leftMiddle(from.union), pointer); return <path d={path} stroke="#70a8f7" className="concept-line-visible draft"/>; })() : null}</svg>
    {rects.map((item, index) => { const colors = graph.connections.filter((edge) => edge.anchorAId === item.anchor.id || edge.anchorBId === item.anchor.id).map((edge) => edge.color); return <span key={`${item.anchor.id}-${index}`} data-concept-anchor-id={item.anchor.id} className={`concept-anchor-box ${item.anchor.status} ${hovered === item.anchor.id ? "hovered" : ""} ${selected === item.anchor.id ? "selected" : ""} ${snapTarget === item.anchor.id ? "snap-target" : ""}`} style={{ left: item.rect.left, top: item.rect.top, width: item.rect.width, height: item.rect.height, borderBottomColor: colors[0], backgroundImage: colors.length > 1 ? `repeating-linear-gradient(90deg, ${colors.map((color, colorIndex) => `${color} ${colorIndex * 8}px, ${color} ${colorIndex * 8 + 3}px, transparent ${colorIndex * 8 + 3}px, transparent ${colorIndex * 8 + 8}px`).join(", ")})` : undefined }}>
      {rects.findIndex((candidate) => candidate.anchor.id === item.anchor.id) === index ? <>{["top", "right", "bottom", "left"].map((side) => <button key={side} className={`connection-handle ${side}`} aria-label="개념 연결 만들기" onPointerDown={(event) => { event.preventDefault(); event.stopPropagation(); snapTargetRef.current = undefined; setSnapTarget(undefined); setDragFrom(item.anchor.id); setPointer({ x: event.clientX, y: event.clientY }); }}/>) }{item.anchor.startOffset != null ? <><button className="range-handle start" aria-label="앵커 시작 범위 조절" onPointerDown={(event) => beginRangeResize(event, item.anchor, "start", graphRef, setGraph)}/><button className="range-handle end" aria-label="앵커 끝 범위 조절" onPointerDown={(event) => beginRangeResize(event, item.anchor, "end", graphRef, setGraph)}/></> : null}{item.anchor.status !== "healthy" ? <i>!</i> : null}</> : null}
    </span>; })}
  </div>, document.body) : null}{menu && typeof document !== "undefined" ? createPortal(<div className="concept-context-menu" style={{ left: menu.x, top: menu.y }} onMouseDown={(event) => event.stopPropagation()}><button onClick={() => void createAnchor()}>개념연결</button></div>, document.body) : null}{connectionMenu && menuConnection && typeof document !== "undefined" ? createPortal(<div className="concept-context-menu connection-delete-menu" style={{ left: connectionMenu.x, top: connectionMenu.y }} onMouseDown={(event) => event.stopPropagation()}><div className="connection-color-section"><span>색상</span><div className="connection-color-palette">{CONNECTION_PALETTE.map((color) => <button type="button" key={color} className={`connection-color-swatch ${menuConnection.color.toLowerCase() === color ? "selected" : ""}`} style={{ backgroundColor: color }} aria-label={`연결 색상 ${color}`} aria-pressed={menuConnection.color.toLowerCase() === color} onClick={() => void updateConnectionColor(menuConnection.id, color)}/>)}</div></div><div className="connection-menu-separator"/><button onClick={() => void deleteConnection(connectionMenu.connectionId)}>연결 삭제</button></div>, document.body) : null}</ConceptContext.Provider>;
}

function selectedOffsets(root: HTMLElement) { if (root instanceof HTMLInputElement || root instanceof HTMLTextAreaElement) { const start = root.selectionStart; const end = root.selectionEnd; return start != null && end != null && end > start ? { start, end, text: root.value.slice(start, end) } : null; } const selection = window.getSelection(); if (!selection?.rangeCount || selection.isCollapsed || !root.contains(selection.anchorNode) || !root.contains(selection.focusNode)) return null; const range = selection.getRangeAt(0); const before = range.cloneRange(); before.selectNodeContents(root); before.setEnd(range.startContainer, range.startOffset); return { start: before.toString().length, end: before.toString().length + range.toString().length, text: range.toString() }; }
function textRangeRects(root: HTMLElement, start: number, end: number) { if (root instanceof HTMLInputElement) { const bounds = root.getBoundingClientRect(); const style = getComputedStyle(root); const canvas = document.createElement("canvas"); const context = canvas.getContext("2d"); if (!context) return [bounds]; context.font = `${style.fontStyle} ${style.fontWeight} ${style.fontSize} ${style.fontFamily}`; const padding = Number.parseFloat(style.paddingLeft) || 0; const left = bounds.left + padding + context.measureText(root.value.slice(0, start)).width - root.scrollLeft; const width = Math.max(2, context.measureText(root.value.slice(start, end)).width); return [new DOMRect(left, bounds.top + bounds.height * .18, width, bounds.height * .64)]; } if (root instanceof HTMLTextAreaElement) return [root.getBoundingClientRect()]; const range = rangeAtOffsets(root, start, end); return range ? [...range.getClientRects()] : []; }
function rangeAtOffsets(root: HTMLElement, start: number, end: number) { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let offset = 0; let startNode: Text | undefined; let endNode: Text | undefined; let startLocal = 0; let endLocal = 0; while (walker.nextNode()) { const node = walker.currentNode as Text; const next = offset + node.length; if (!startNode && start <= next) { startNode = node; startLocal = Math.max(0, start - offset); } if (end <= next) { endNode = node; endLocal = Math.max(0, end - offset); break; } offset = next; } if (!startNode || !endNode) return null; const range = document.createRange(); range.setStart(startNode, Math.min(startLocal, startNode.length)); range.setEnd(endNode, Math.min(endLocal, endNode.length)); return range; }
function unionRects(rects: DOMRect[]) { const left = Math.min(...rects.map((rect) => rect.left)); const top = Math.min(...rects.map((rect) => rect.top)); const right = Math.max(...rects.map((rect) => rect.right)); const bottom = Math.max(...rects.map((rect) => rect.bottom)); return new DOMRect(left, top, right - left, bottom - top); }
function uniqueRects(rects: RectState[]) { return [...new Map(rects.map((item) => [item.anchor.id, { ...item, rect: item.union }])).values()]; }
function pointIn(x: number, y: number, rect: DOMRect) { return x >= rect.left - 8 && x <= rect.right + 8 && y >= rect.top - 8 && y <= rect.bottom + 8; }
function distanceToRect(x: number, y: number, rect: DOMRect) { const dx = Math.max(rect.left - x, 0, x - rect.right); const dy = Math.max(rect.top - y, 0, y - rect.bottom); return Math.hypot(dx, dy); }
function nearestSnapTarget(anchors: RectState[], x: number, y: number, sourceId: string) { return anchors.filter((item) => item.anchor.id !== sourceId && item.anchor.status !== "broken").map((item) => ({ item, distance: distanceToRect(x, y, item.union) })).filter(({ distance }) => distance <= 28).sort((left, right) => left.distance - right.distance)[0]?.item; }
function leftMiddle(rect: DOMRect) { return { x: rect.left, y: rect.top + rect.height / 2 }; }
function connectionPath(a?: RectState, b?: RectState, edge?: ConceptConnection, connections: ConceptConnection[] = []) { const mounted = a ?? b!; const start = a ? connectionAttachment(a.union, edge?.anchorAId, edge?.id, connections) : { x: Math.max(12, mounted.union.left - 44), y: mounted.union.top + mounted.union.height / 2 }; const end = b ? connectionAttachment(b.union, edge?.anchorBId, edge?.id, connections) : { x: Math.max(12, mounted.union.left - 44), y: mounted.union.top + mounted.union.height / 2 }; const contentLefts = [a?.contentLeft, b?.contentLeft, a?.field?.left, b?.field?.left].filter((value): value is number => value != null); const referenceLeft = contentLefts.length ? Math.min(...contentLefts) : Math.min(start.x, end.x); const laneIndex = edge ? connectionLaneIndex(edge, connections) : 0; const gutterX = Math.max(12, referenceLeft - 32 - laneIndex * 8); return `M ${start.x} ${start.y} H ${gutterX} V ${end.y} H ${end.x}`; }
function connectionAttachment(rect: DOMRect, anchorId?: string, edgeId?: string, connections: ConceptConnection[] = []) { if (!anchorId || !edgeId) return leftMiddle(rect); const siblings = connections.filter((edge) => edge.anchorAId === anchorId || edge.anchorBId === anchorId).sort((left, right) => left.id.localeCompare(right.id)); const index = siblings.findIndex((edge) => edge.id === edgeId); const ratio = siblings.length <= 1 || index < 0 ? .5 : .3 + (.4 * index) / (siblings.length - 1); return { x: rect.left, y: rect.top + rect.height * ratio }; }
function connectionLaneIndex(edge: ConceptConnection, connections: ConceptConnection[]) { const siblingIndex = (anchorId: string) => connections.filter((candidate) => candidate.anchorAId === anchorId || candidate.anchorBId === anchorId).sort((left, right) => left.id.localeCompare(right.id)).findIndex((candidate) => candidate.id === edge.id); return Math.max(0, siblingIndex(edge.anchorAId), siblingIndex(edge.anchorBId)); }
function orthogonalPath(a: { x: number; y: number }, b: { x: number; y: number }) { const middle = (a.x + b.x) / 2; return `M ${a.x} ${a.y} H ${middle} V ${b.y} H ${b.x}`; }
function isEditableTarget(target: EventTarget | null) { return target instanceof HTMLElement && (target.isContentEditable || target.matches("input, textarea, select") || Boolean(target.closest("[contenteditable='true']"))); }
function textEdit(before: string, after: string) { let start = 0; while (start < before.length && start < after.length && before[start] === after[start]) start++; let suffix = 0; while (suffix < before.length - start && suffix < after.length - start && before[before.length - 1 - suffix] === after[after.length - 1 - suffix]) suffix++; return { start, oldEnd: before.length - suffix, inserted: after.slice(start, after.length - suffix) }; }
export function adjustAnchorRange(start: number, end: number, editStart: number, editEnd: number, insertedLength: number) { const removed = editEnd - editStart; const delta = insertedLength - removed; if (editEnd <= start) return { start: start + delta, end: end + delta }; if (editStart >= end) return { start, end }; const nextStart = Math.min(start, editStart); const retainedBefore = Math.max(0, editStart - start); const retainedAfter = Math.max(0, end - editEnd); return { start: nextStart, end: nextStart + retainedBefore + insertedLength + retainedAfter }; }
function beginRangeResize(event: React.PointerEvent, anchor: ConceptAnchor, side: "start" | "end", graphRef: React.MutableRefObject<Graph>, setGraph: React.Dispatch<React.SetStateAction<Graph>>) { event.preventDefault(); event.stopPropagation(); const serializedTargetRef = serializeConceptAnchorTargetRef(anchor.targetRef); const resolveTarget = () => [...document.querySelectorAll<HTMLElement>(`[data-concept-owner-id="${anchor.ownerId}"][data-concept-target-ref]`)].find((node) => node.dataset.conceptTargetRef === serializedTargetRef); const move = (pointer: PointerEvent) => { const target = resolveTarget(); if (!target) return; let offset: number | undefined; if (target instanceof HTMLInputElement) offset = inputOffsetAtPoint(target, pointer.clientX); else { const caret = document.caretPositionFromPoint?.(pointer.clientX, pointer.clientY); if (!caret || !target.contains(caret.offsetNode)) return; const before = document.createRange(); before.selectNodeContents(target); before.setEnd(caret.offsetNode, caret.offset); offset = before.toString().length; } const patch = side === "start" ? { startOffset: Math.min(offset, (anchor.endOffset ?? offset + 1) - 1) } : { endOffset: Math.max(offset, (anchor.startOffset ?? 0) + 1) }; setGraph((current) => ({ ...current, anchors: current.anchors.map((item) => item.id === anchor.id ? { ...item, ...patch, status: "healthy" } : item) })); }; const up = () => { const current = graphRef.current.anchors.find((item) => item.id === anchor.id); const target = resolveTarget(); if (current) { const text = target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement ? target.value : target?.innerText ?? ""; const snapshotText = current.startOffset != null && current.endOffset != null ? text.slice(current.startOffset, current.endOffset) : current.snapshotText; setGraph((state) => ({ ...state, anchors: state.anchors.map((item) => item.id === current.id ? { ...item, snapshotText } : item) })); void fetch(`/api/concept-anchors/${anchor.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startOffset: current.startOffset, endOffset: current.endOffset, snapshotText, status: "healthy", refreshSnapshots: true }) }); } window.removeEventListener("pointermove", move); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); }
function inputOffsetAtPoint(input: HTMLInputElement, clientX: number) { const bounds = input.getBoundingClientRect(); const style = getComputedStyle(input); const canvas = document.createElement("canvas"); const context = canvas.getContext("2d"); if (!context) return input.value.length; context.font = `${style.fontStyle} ${style.fontWeight} ${style.fontSize} ${style.fontFamily}`; const x = clientX - bounds.left - (Number.parseFloat(style.paddingLeft) || 0) + input.scrollLeft; let best = 0; let distance = Number.POSITIVE_INFINITY; for (let index = 0; index <= input.value.length; index++) { const next = Math.abs(context.measureText(input.value.slice(0, index)).width - x); if (next < distance) { distance = next; best = index; } } return best; }
