"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { ConceptAnchorStatus, ConceptAnchorTargetRef, ConceptOwnerType, ConceptTargetType } from "@/lib/db/schema";

export type ConceptAnchor = { id: string; ownerType: ConceptOwnerType; ownerId: string; targetType: ConceptTargetType; targetRef: ConceptAnchorTargetRef; startOffset: number | null; endOffset: number | null; status: ConceptAnchorStatus; snapshotText: string | null; snapshotHash: string | null; assetVersion: string | null };
export type ConceptConnection = { id: string; anchorAId: string; anchorBId: string; color: string; anchorASnapshot: { text?: string; hash?: string; assetVersion?: string }; anchorBSnapshot: { text?: string; hash?: string; assetVersion?: string }; historicalA: boolean; historicalB: boolean };
export type ConceptTarget = { ownerType: ConceptOwnerType; ownerId: string; targetType: ConceptTargetType; targetRef: ConceptAnchorTargetRef };
type Graph = { anchors: ConceptAnchor[]; connections: ConceptConnection[] };
type MenuState = { x: number; y: number; target: ConceptTarget; startOffset: number | null; endOffset: number | null; text: string; assetVersion?: string };
type RectState = { anchor: ConceptAnchor; rect: DOMRect; union: DOMRect };
type ConceptContextValue = { graph: Graph; reload: () => Promise<void>; openMenu: (event: React.MouseEvent<HTMLElement>, target: ConceptTarget, wholeText?: string, assetVersion?: string) => boolean; reconcileText: (target: ConceptTarget, before: string, after: string) => boolean; breakTarget: (target: ConceptTarget) => Promise<void>; selectAnchor: (id?: string) => void };

const ConceptContext = createContext<ConceptContextValue | null>(null);
const targetKey = (target: ConceptTarget | ConceptAnchor) => `${target.ownerType}:${target.ownerId}:${target.targetType}:${JSON.stringify(target.targetRef)}`;
const sameTarget = (anchor: ConceptAnchor, target: ConceptTarget) => targetKey(anchor) === targetKey(target);

export function useConceptEngine() { return useContext(ConceptContext); }
export function conceptTargetAttributes(target: ConceptTarget) { return { "data-concept-owner-type": target.ownerType, "data-concept-owner-id": target.ownerId, "data-concept-target-type": target.targetType, "data-concept-target-ref": JSON.stringify(target.targetRef) } as const; }

export function ConceptBoundary({ ownerType, ownerId, children, onNavigate }: { ownerType: ConceptOwnerType; ownerId: string; children: React.ReactNode; onNavigate?: (anchor: ConceptAnchor, connection: ConceptConnection) => void }) {
  const existing = useConceptEngine();
  return existing ? children : <ConceptProvider ownerType={ownerType} ownerId={ownerId} onNavigate={onNavigate}>{children}</ConceptProvider>;
}

export function ConceptProvider({ ownerType, ownerId, children, onNavigate }: { ownerType: ConceptOwnerType; ownerId: string; children: React.ReactNode; onNavigate?: (anchor: ConceptAnchor, connection: ConceptConnection) => void }) {
  const [graph, setGraph] = useState<Graph>({ anchors: [], connections: [] }); const [menu, setMenu] = useState<MenuState>(); const [rects, setRects] = useState<RectState[]>([]); const [hovered, setHovered] = useState<string>(); const [selected, setSelected] = useState<string>(); const [dragFrom, setDragFrom] = useState<string>(); const [pointer, setPointer] = useState<{ x: number; y: number }>(); const graphRef = useRef(graph); graphRef.current = graph;
  const reload = useCallback(async () => { const response = await fetch(`/api/concept-anchors?ownerType=${ownerType}&ownerId=${ownerId}`); if (response.ok) setGraph(await response.json()); }, [ownerId, ownerType]);
  useEffect(() => { void reload(); }, [reload]);

  const calculate = useCallback(() => {
    const next: RectState[] = [];
    for (const anchor of graphRef.current.anchors) {
      const selector = `[data-concept-owner-type="${anchor.ownerType}"][data-concept-owner-id="${anchor.ownerId}"][data-concept-target-type="${anchor.targetType}"]`;
      const nodes = [...document.querySelectorAll<HTMLElement>(selector)]; const node = nodes.find((candidate) => candidate.dataset.conceptTargetRef === JSON.stringify(anchor.targetRef)); if (!node) continue;
      const clientRects = anchor.startOffset != null && anchor.endOffset != null ? textRangeRects(node, anchor.startOffset, anchor.endOffset) : [node.getBoundingClientRect()];
      const visible = clientRects.filter((rect) => rect.width > 0 && rect.height > 0); if (!visible.length) continue;
      const union = unionRects(visible); for (const rect of visible) next.push({ anchor, rect, union });
    }
    setRects(next);
  }, []);
  useEffect(() => { calculate(); const observer = new ResizeObserver(calculate); observer.observe(document.body); const handler = () => calculate(); window.addEventListener("scroll", handler, true); window.addEventListener("resize", handler); return () => { observer.disconnect(); window.removeEventListener("scroll", handler, true); window.removeEventListener("resize", handler); }; }, [calculate, graph]);
  useEffect(() => { const move = (event: PointerEvent) => { if (dragFrom) return; const hit = uniqueRects(rects).find((item) => pointIn(event.clientX, event.clientY, item.union)); setHovered(hit?.anchor.id); }; window.addEventListener("pointermove", move); return () => window.removeEventListener("pointermove", move); }, [dragFrom, rects]);

  const openMenu = useCallback((event: React.MouseEvent<HTMLElement>, target: ConceptTarget, wholeText?: string, assetVersion?: string) => {
    const node = event.currentTarget; const range = selectedOffsets(node); const text = range ? range.text : wholeText;
    if (!text && !assetVersion) return false; event.preventDefault(); setMenu({ x: event.clientX, y: event.clientY, target, startOffset: range?.start ?? null, endOffset: range?.end ?? null, text: text ?? "", assetVersion }); return true;
  }, []);
  async function createAnchor() { if (!menu) return; const response = await fetch("/api/concept-anchors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...menu.target, startOffset: menu.startOffset, endOffset: menu.endOffset, snapshotText: menu.text || undefined, assetVersion: menu.assetVersion }) }); setMenu(undefined); if (response.ok) { const anchor = await response.json(); setSelected(anchor.id); setGraph((current) => ({ ...current, anchors: current.anchors.some((item) => item.id === anchor.id) ? current.anchors : [...current.anchors, anchor] })); } }

  const reconcileText = useCallback((target: ConceptTarget, before: string, after: string) => {
    if (before === after) return true; const edit = textEdit(before, after); const affected = graphRef.current.anchors.filter((anchor) => sameTarget(anchor, target) && anchor.startOffset != null && anchor.endOffset != null && anchor.status !== "broken");
    const changes = affected.map((anchor) => ({ anchor, adjusted: adjustAnchorRange(anchor.startOffset!, anchor.endOffset!, edit.start, edit.oldEnd, edit.inserted.length) }));
    if (changes.some(({ adjusted }) => adjusted.end <= adjusted.start) && !window.confirm("연결된 개념 관계가 이 앵커에 의존합니다. 마지막 앵커 내용을 삭제하면 연결은 유지되지만 끝점이 누락 상태가 됩니다. 계속할까요?")) return false;
    for (const { anchor, adjusted } of changes) {
      const vanished = adjusted.end <= adjusted.start;
      const snapshotText = vanished ? anchor.snapshotText : after.slice(adjusted.start, adjusted.end);
      const patch = vanished ? { status: "broken" } : { startOffset: adjusted.start, endOffset: adjusted.end, snapshotText, status: graphRef.current.connections.some((edge) => edge.anchorAId === anchor.id || edge.anchorBId === anchor.id) ? "updated" : "healthy" };
      setGraph((current) => ({ ...current, anchors: current.anchors.map((item) => item.id === anchor.id ? { ...item, ...patch } as ConceptAnchor : item) }));
      void fetch(`/api/concept-anchors/${anchor.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) });
    }
    return true;
  }, []);
  const breakTarget = useCallback(async (target: ConceptTarget) => { const matches = graphRef.current.anchors.filter((anchor) => sameTarget(anchor, target) && anchor.status !== "broken"); if (matches.length && !window.confirm("이 콘텐츠에 연결된 개념 관계가 있습니다. 삭제 후에도 연결 기록은 남고 누락 상태로 표시됩니다. 계속할까요?")) return; await Promise.all(matches.map((anchor) => fetch(`/api/concept-anchors/${anchor.id}`, { method: "DELETE" }))); await reload(); }, [reload]);

  async function connect(toId: string) { if (!dragFrom || dragFrom === toId) return; const response = await fetch("/api/concept-connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ anchorAId: dragFrom, anchorBId: toId }) }); setDragFrom(undefined); setPointer(undefined); if (response.ok) { const edge = await response.json(); setSelected(edge.id); await reload(); } }
  useEffect(() => { if (!dragFrom) return; const move = (event: PointerEvent) => setPointer({ x: event.clientX, y: event.clientY }); const up = (event: PointerEvent) => { const hit = uniqueRects(rects).find((item) => pointIn(event.clientX, event.clientY, item.union) && item.anchor.id !== dragFrom); if (hit) void connect(hit.anchor.id); else { setDragFrom(undefined); setPointer(undefined); } }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return () => window.removeEventListener("pointermove", move); });
  useEffect(() => { const dismiss = () => setMenu(undefined); const key = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenu(undefined); setDragFrom(undefined); setPointer(undefined); } }; window.addEventListener("mousedown", dismiss); window.addEventListener("keydown", key); return () => { window.removeEventListener("mousedown", dismiss); window.removeEventListener("keydown", key); }; }, []);

  const value = useMemo<ConceptContextValue>(() => ({ graph, reload, openMenu, reconcileText, breakTarget, selectAnchor: setSelected }), [breakTarget, graph, openMenu, reconcileText, reload]);
  const anchors = uniqueRects(rects); const activeConnections = graph.connections.filter((edge) => [hovered, selected].includes(edge.id) || [edge.anchorAId, edge.anchorBId].includes(hovered ?? "") || [edge.anchorAId, edge.anchorBId].includes(selected ?? ""));
  return <ConceptContext.Provider value={value}>{children}{typeof document !== "undefined" ? createPortal(<div className="concept-overlay" aria-hidden={!dragFrom}>
    <svg className="concept-lines">{activeConnections.map((edge) => { const a = anchors.find((item) => item.anchor.id === edge.anchorAId)?.union; const b = anchors.find((item) => item.anchor.id === edge.anchorBId)?.union; if (!a && !b) return null; const start = a ? center(a) : { x: 78, y: b!.top + b!.height / 2 }; const end = b ? center(b) : { x: 78, y: a!.top + a!.height / 2 }; const path = orthogonalPath(start, end); return <path key={edge.id} d={path} stroke={edge.color} className={selected === edge.id ? "selected" : ""} onPointerEnter={() => setHovered(edge.id)} onPointerLeave={() => setHovered(undefined)} onClick={() => { setSelected(edge.id); const mountedId = a ? edge.anchorAId : edge.anchorBId; const otherId = mountedId === edge.anchorAId ? edge.anchorBId : edge.anchorAId; const other = graph.anchors.find((anchor) => anchor.id === otherId); if (other) onNavigate?.(other, edge); }}/>; })}{dragFrom && pointer ? (() => { const from = anchors.find((item) => item.anchor.id === dragFrom)?.union; return from ? <path d={orthogonalPath(center(from), pointer)} stroke="#70a8f7" className="draft"/> : null; })() : null}</svg>
    {rects.map((item, index) => { const colors = graph.connections.filter((edge) => edge.anchorAId === item.anchor.id || edge.anchorBId === item.anchor.id).map((edge) => edge.color); return <span key={`${item.anchor.id}-${index}`} className={`concept-anchor-box ${item.anchor.status} ${hovered === item.anchor.id ? "hovered" : ""} ${selected === item.anchor.id ? "selected" : ""}`} style={{ left: item.rect.left, top: item.rect.top, width: item.rect.width, height: item.rect.height, borderBottomColor: colors[0], backgroundImage: colors.length > 1 ? `repeating-linear-gradient(90deg, ${colors.map((color, colorIndex) => `${color} ${colorIndex * 8}px, ${color} ${colorIndex * 8 + 3}px, transparent ${colorIndex * 8 + 3}px, transparent ${colorIndex * 8 + 8}px`).join(", ")})` : undefined }} onPointerEnter={() => setHovered(item.anchor.id)} onPointerLeave={() => setHovered(undefined)} onClick={() => { setSelected(item.anchor.id); const edges = graph.connections.filter((candidate) => candidate.anchorAId === item.anchor.id || candidate.anchorBId === item.anchor.id); let edge = edges[0]; if (edges.length > 1) { const choices = edges.map((candidate, choiceIndex) => { const otherId = candidate.anchorAId === item.anchor.id ? candidate.anchorBId : candidate.anchorAId; const other = graph.anchors.find((anchor) => anchor.id === otherId); return `${choiceIndex + 1}. ${other?.snapshotText || other?.targetType || "연결"}`; }); const choice = Number(window.prompt(`열 소스를 선택하세요:\n${choices.join("\n")}`, "1")); edge = edges[choice - 1] ?? edges[0]; } if (edge) { const otherId = edge.anchorAId === item.anchor.id ? edge.anchorBId : edge.anchorAId; const other = graph.anchors.find((anchor) => anchor.id === otherId); if (other) onNavigate?.(other, edge); } }}>
      {item.union === item.rect ? <>{["top", "right", "bottom", "left"].map((side) => <button key={side} className={`connection-handle ${side}`} aria-label="개념 연결 만들기" onPointerDown={(event) => { event.stopPropagation(); setDragFrom(item.anchor.id); setPointer({ x: event.clientX, y: event.clientY }); }}/>) }{item.anchor.startOffset != null ? <><button className="range-handle start" aria-label="앵커 시작 범위 조절" onPointerDown={(event) => beginRangeResize(event, item.anchor, "start", graphRef, setGraph)}/><button className="range-handle end" aria-label="앵커 끝 범위 조절" onPointerDown={(event) => beginRangeResize(event, item.anchor, "end", graphRef, setGraph)}/></> : null}{item.anchor.status !== "healthy" ? <i>!</i> : null}</> : null}
    </span>; })}
  </div>, document.body) : null}{menu && typeof document !== "undefined" ? createPortal(<div className="concept-context-menu" style={{ left: menu.x, top: menu.y }} onMouseDown={(event) => event.stopPropagation()}><button onClick={() => void createAnchor()}>개념연결</button></div>, document.body) : null}</ConceptContext.Provider>;
}

function selectedOffsets(root: HTMLElement) { if (root instanceof HTMLInputElement || root instanceof HTMLTextAreaElement) { const start = root.selectionStart; const end = root.selectionEnd; return start != null && end != null && end > start ? { start, end, text: root.value.slice(start, end) } : null; } const selection = window.getSelection(); if (!selection?.rangeCount || selection.isCollapsed || !root.contains(selection.anchorNode) || !root.contains(selection.focusNode)) return null; const range = selection.getRangeAt(0); const before = range.cloneRange(); before.selectNodeContents(root); before.setEnd(range.startContainer, range.startOffset); return { start: before.toString().length, end: before.toString().length + range.toString().length, text: range.toString() }; }
function textRangeRects(root: HTMLElement, start: number, end: number) { if (root instanceof HTMLInputElement) { const bounds = root.getBoundingClientRect(); const style = getComputedStyle(root); const canvas = document.createElement("canvas"); const context = canvas.getContext("2d"); if (!context) return [bounds]; context.font = `${style.fontStyle} ${style.fontWeight} ${style.fontSize} ${style.fontFamily}`; const padding = Number.parseFloat(style.paddingLeft) || 0; const left = bounds.left + padding + context.measureText(root.value.slice(0, start)).width - root.scrollLeft; const width = Math.max(2, context.measureText(root.value.slice(start, end)).width); return [new DOMRect(left, bounds.top + bounds.height * .18, width, bounds.height * .64)]; } if (root instanceof HTMLTextAreaElement) return [root.getBoundingClientRect()]; const range = rangeAtOffsets(root, start, end); return range ? [...range.getClientRects()] : []; }
function rangeAtOffsets(root: HTMLElement, start: number, end: number) { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let offset = 0; let startNode: Text | undefined; let endNode: Text | undefined; let startLocal = 0; let endLocal = 0; while (walker.nextNode()) { const node = walker.currentNode as Text; const next = offset + node.length; if (!startNode && start <= next) { startNode = node; startLocal = Math.max(0, start - offset); } if (end <= next) { endNode = node; endLocal = Math.max(0, end - offset); break; } offset = next; } if (!startNode || !endNode) return null; const range = document.createRange(); range.setStart(startNode, Math.min(startLocal, startNode.length)); range.setEnd(endNode, Math.min(endLocal, endNode.length)); return range; }
function unionRects(rects: DOMRect[]) { const left = Math.min(...rects.map((rect) => rect.left)); const top = Math.min(...rects.map((rect) => rect.top)); const right = Math.max(...rects.map((rect) => rect.right)); const bottom = Math.max(...rects.map((rect) => rect.bottom)); return new DOMRect(left, top, right - left, bottom - top); }
function uniqueRects(rects: RectState[]) { return [...new Map(rects.map((item) => [item.anchor.id, { ...item, rect: item.union }])).values()]; }
function center(rect: DOMRect) { return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 }; }
function pointIn(x: number, y: number, rect: DOMRect) { return x >= rect.left - 8 && x <= rect.right + 8 && y >= rect.top - 8 && y <= rect.bottom + 8; }
function orthogonalPath(a: { x: number; y: number }, b: { x: number; y: number }) { const middle = (a.x + b.x) / 2; return `M ${a.x} ${a.y} H ${middle} V ${b.y} H ${b.x}`; }
function textEdit(before: string, after: string) { let start = 0; while (start < before.length && start < after.length && before[start] === after[start]) start++; let suffix = 0; while (suffix < before.length - start && suffix < after.length - start && before[before.length - 1 - suffix] === after[after.length - 1 - suffix]) suffix++; return { start, oldEnd: before.length - suffix, inserted: after.slice(start, after.length - suffix) }; }
export function adjustAnchorRange(start: number, end: number, editStart: number, editEnd: number, insertedLength: number) { const removed = editEnd - editStart; const delta = insertedLength - removed; if (editEnd <= start) return { start: start + delta, end: end + delta }; if (editStart >= end) return { start, end }; const nextStart = Math.min(start, editStart); const retainedBefore = Math.max(0, editStart - start); const retainedAfter = Math.max(0, end - editEnd); return { start: nextStart, end: nextStart + retainedBefore + insertedLength + retainedAfter }; }
function beginRangeResize(event: React.PointerEvent, anchor: ConceptAnchor, side: "start" | "end", graphRef: React.MutableRefObject<Graph>, setGraph: React.Dispatch<React.SetStateAction<Graph>>) { event.preventDefault(); event.stopPropagation(); const move = (pointer: PointerEvent) => { const target = document.elementFromPoint(pointer.clientX, pointer.clientY)?.closest<HTMLElement>("[data-concept-target-ref]"); if (!target || target.dataset.conceptOwnerId !== anchor.ownerId || target.dataset.conceptTargetRef !== JSON.stringify(anchor.targetRef)) return; const caret = document.caretPositionFromPoint?.(pointer.clientX, pointer.clientY); if (!caret || !target.contains(caret.offsetNode)) return; const before = document.createRange(); before.selectNodeContents(target); before.setEnd(caret.offsetNode, caret.offset); const offset = before.toString().length; const patch = side === "start" ? { startOffset: Math.min(offset, (anchor.endOffset ?? offset + 1) - 1) } : { endOffset: Math.max(offset, (anchor.startOffset ?? 0) + 1) }; setGraph((current) => ({ ...current, anchors: current.anchors.map((item) => item.id === anchor.id ? { ...item, ...patch, status: "healthy" } : item) })); }; const up = () => { const current = graphRef.current.anchors.find((item) => item.id === anchor.id); const target = [...document.querySelectorAll<HTMLElement>(`[data-concept-owner-id="${anchor.ownerId}"][data-concept-target-ref]`)].find((node) => node.dataset.conceptTargetRef === JSON.stringify(anchor.targetRef)); if (current) { const text = target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement ? target.value : target?.innerText ?? ""; const snapshotText = current.startOffset != null && current.endOffset != null ? text.slice(current.startOffset, current.endOffset) : current.snapshotText; setGraph((state) => ({ ...state, anchors: state.anchors.map((item) => item.id === current.id ? { ...item, snapshotText } : item) })); void fetch(`/api/concept-anchors/${anchor.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startOffset: current.startOffset, endOffset: current.endOffset, snapshotText, status: "healthy", refreshSnapshots: true }) }); } window.removeEventListener("pointermove", move); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); }
