"use client";
import { Plus, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import type { FieldInputMode } from "@/lib/db/schema";
type Field = { id: string; name: string; kind: "default" | "custom"; inputMode: FieldInputMode; position: number };
export function FieldsSettings() {
  const [fields, setFields] = useState<Field[]>([]); const [name, setName] = useState(""); const [mode, setMode] = useState<FieldInputMode>("hierarchy4");
  useEffect(() => { fetch("/api/field-definitions").then((response) => response.json()).then(setFields); }, []);
  function patch(id: string, value: Partial<Field>) { setFields((current) => current.map((field) => field.id === id ? { ...field, ...value } : field)); }
  async function save(field: Field) { const response = await fetch(`/api/field-definitions/${field.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: field.name, inputMode: field.inputMode }) }); if (!response.ok) window.alert("Field를 저장하지 못했습니다."); }
  async function archive(field: Field) { if (!window.confirm(`“${field.name}”을 보관 처리할까요? 기존 카드 내용은 유지됩니다.`)) return; const response = await fetch(`/api/field-definitions/${field.id}`, { method: "DELETE" }); if (response.ok) setFields((current) => current.filter((item) => item.id !== field.id)); }
  async function create() { if (!name.trim()) return; const response = await fetch("/api/field-definitions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), inputMode: mode }) }); const body = await response.json(); if (!response.ok) { window.alert(body.error ?? "Field를 추가하지 못했습니다."); return; } setFields((current) => [...current, body]); setName(""); }
  return <section className="settings-section panel"><h2>Fields</h2><p className="muted">기본 Field의 입력 형식을 확인하고, 재사용 가능한 사용자 정의 Field를 관리합니다.</p><div className="settings-fields-list">{fields.map((field) => <div key={field.id}><span className={`field-kind ${field.kind}`}>{field.kind === "default" ? "기본" : "사용자"}</span><input value={field.name} disabled={field.kind === "default"} onChange={(event) => patch(field.id, { name: event.target.value })}/><select value={field.inputMode} disabled={field.kind === "default"} onChange={(event) => patch(field.id, { inputMode: event.target.value as FieldInputMode })}><option value="hierarchy4">i) → ① → a) → •</option><option value="hierarchy3">① → a) → •</option><option value="text">일반 텍스트</option></select><button disabled={field.kind === "default"} onClick={() => void save(field)} title="저장"><Save size={15}/></button><button disabled={field.kind === "default"} onClick={() => void archive(field)} title="보관"><Trash2 size={15}/></button></div>)}</div><div className="settings-new-field"><Plus size={16}/><input value={name} onChange={(event) => setName(event.target.value)} placeholder="새 사용자 Field"/><select value={mode} onChange={(event) => setMode(event.target.value as FieldInputMode)}><option value="hierarchy4">4단계 위계</option><option value="hierarchy3">3단계 위계</option><option value="text">일반 텍스트</option></select><button onClick={() => void create()}>추가</button></div></section>;
}
