"use client";

import { AlignCenter, AlignLeft, AlignRight, Bold, Columns3, Highlighter, Italic, Merge, Rows3, SplitSquareHorizontal, Trash2, WrapText } from "lucide-react";
import { memo, useEffect, useMemo, useRef, useState } from "react";
import type { CollectionTableBlock, TableCell, TableRange } from "@/lib/db/schema";
import { conceptTargetAttributes, type ConceptTarget, useConceptEngine } from "@/components/concept-engine";
import { useLatexShortcuts } from "@/components/use-latex-shortcuts";
import { applyLatexShortcuts } from "@/lib/latex-shortcuts";

type Position = { row: number; column: number };
type Props = { block: CollectionTableBlock; collectionId: string; onChange: (block: CollectionTableBlock) => void };
const keyOf = (row: number, column: number) => `${row}:${column}`;
const normalize = (range: TableRange): TableRange => ({ startRow: Math.min(range.startRow, range.endRow), endRow: Math.max(range.startRow, range.endRow), startColumn: Math.min(range.startColumn, range.endColumn), endColumn: Math.max(range.startColumn, range.endColumn) });
const includes = (range: TableRange, row: number, column: number) => { const value = normalize(range); return row >= value.startRow && row <= value.endRow && column >= value.startColumn && column <= value.endColumn; };

export const SpreadsheetBlock = memo(function SpreadsheetBlock({ block, collectionId, onChange }: Props) {
  const [active, setActive] = useState<Position>({ row: 0, column: 0 }); const [anchor, setAnchor] = useState(active); const [ranges, setRanges] = useState<TableRange[]>([{ startRow: 0, startColumn: 0, endRow: 0, endColumn: 0 }]); const [editing, setEditing] = useState<Position>(); const [dragging, setDragging] = useState(false); const [clipboardRange, setClipboardRange] = useState<TableRange>(); const undo = useRef<CollectionTableBlock[]>([]); const redo = useRef<CollectionTableBlock[]>([]); const root = useRef<HTMLDivElement>(null); const concepts = useConceptEngine();
  const shortcuts = useLatexShortcuts();
  const commit = (next: CollectionTableBlock, record = true) => { if (record) { undo.current.push(structuredClone(block)); if (undo.current.length > 50) undo.current.shift(); redo.current = []; } onChange(next); };
  const cell = (row: number, column: number) => block.cells[keyOf(row, column)] ?? { id: crypto.randomUUID(), text: "" };
  const updateCell = (row: number, column: number, patch: Partial<TableCell>) => commit({ ...block, cells: { ...block.cells, [keyOf(row, column)]: { ...cell(row, column), ...patch } } });
  const selected = (row: number, column: number) => ranges.some((range) => includes(range, row, column));
  function select(position: Position, extend: boolean, additive: boolean) { setActive(position); if (extend) { const range = { startRow: anchor.row, startColumn: anchor.column, endRow: position.row, endColumn: position.column }; setRanges((current) => additive ? [...current.slice(0, -1), range] : [range]); } else { setAnchor(position); const range = { startRow: position.row, startColumn: position.column, endRow: position.row, endColumn: position.column }; setRanges((current) => additive ? [...current, range] : [range]); } }
  function mutateSelected(patch: Partial<TableCell>) { const cells = { ...block.cells }; for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) cells[keyOf(row, column)] = { ...cell(row, column), ...patch }; } commit({ ...block, cells }); }
  async function clearSelected() { const cells = { ...block.cells }; const cellIds: string[] = []; for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) { cellIds.push(cell(row, column).id); cells[keyOf(row, column)] = { ...cell(row, column), text: "", html: "" }; } } if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds }) === false) return; commit({ ...block, cells }); }
  async function copy() { if (ranges.length !== 1) { window.alert("여러 비연속 범위는 한 번에 복사할 수 없습니다. 하나의 직사각형 범위를 선택하세요."); return; } const range = normalize(ranges[0]); const tsv = Array.from({ length: range.endRow - range.startRow + 1 }, (_, row) => Array.from({ length: range.endColumn - range.startColumn + 1 }, (_, column) => cell(range.startRow + row, range.startColumn + column).text).join("\t")).join("\n"); await navigator.clipboard.writeText(tsv); setClipboardRange(range); }
  function pasteText(text: string) { const grid = text.replace(/\r/g, "").split("\n").map((row) => row.split("\t")); const rows = Math.max(block.rows, active.row + grid.length); const columns = Math.max(block.columns, active.column + Math.max(...grid.map((row) => row.length))); const cells = { ...block.cells }; for (let row = 0; row < rows; row++) for (let column = 0; column < columns; column++) cells[keyOf(row, column)] ??= { id: crypto.randomUUID(), text: "" }; grid.forEach((values, row) => values.forEach((textValue, column) => { const position = keyOf(active.row + row, active.column + column); cells[position] = { ...cells[position], text: textValue, html: escapeHtml(textValue) }; })); commit({ ...block, rows, columns, cells, rowSizes: fillSizes(block.rowSizes, rows, 34), columnSizes: fillSizes(block.columnSizes, columns, 128) }); }
  function move(rowDelta: number, columnDelta: number, extend: boolean) { const position = { row: Math.max(0, Math.min(block.rows - 1, active.row + rowDelta)), column: Math.max(0, Math.min(block.columns - 1, active.column + columnDelta)) }; select(position, extend, false); requestAnimationFrame(() => root.current?.querySelector<HTMLElement>(`[data-cell="${position.row}:${position.column}"]`)?.focus()); }
  function history(direction: "undo" | "redo") { const from = direction === "undo" ? undo : redo; const to = direction === "undo" ? redo : undo; const previous = from.current.pop(); if (!previous) return; to.current.push(structuredClone(block)); onChange(previous); }
  function keyDown(event: React.KeyboardEvent) { if (editing) { if (event.key === "Escape") { setEditing(undefined); root.current?.focus(); } return; } const command = event.metaKey || event.ctrlKey; if (command && event.key.toLowerCase() === "c") { event.preventDefault(); void copy(); return; } if (command && event.key.toLowerCase() === "v") { event.preventDefault(); void navigator.clipboard.readText().then(pasteText); return; } if (command && event.key.toLowerCase() === "b") { event.preventDefault(); mutateSelected({ bold: true }); return; } if (command && event.key.toLowerCase() === "i") { event.preventDefault(); mutateSelected({ italic: true }); return; } if (command && event.key.toLowerCase() === "z") { event.preventDefault(); history(event.shiftKey ? "redo" : "undo"); return; } if (event.key === "Escape") { setClipboardRange(undefined); return; } if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); void clearSelected(); return; } const movements: Record<string, [number, number]> = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1], Tab: [0, event.shiftKey ? -1 : 1], Enter: [event.shiftKey ? -1 : 1, 0] }; const movement = movements[event.key]; if (movement) { event.preventDefault(); move(movement[0], movement[1], event.shiftKey && event.key.startsWith("Arrow")); } }
  async function merge() { if (ranges.length !== 1) return window.alert("병합은 하나의 연속된 직사각형 범위에서만 사용할 수 있습니다."); const range = normalize(ranges[0]); if (range.startRow === range.endRow && range.startColumn === range.endColumn) return; const populated: string[] = []; const discardedIds: string[] = []; for (let row = range.startRow; row <= range.endRow; row++) for (let column = range.startColumn; column <= range.endColumn; column++) if (row !== range.startRow || column !== range.startColumn) { discardedIds.push(cell(row, column).id); if (cell(row, column).text) populated.push(cell(row, column).text); } if (populated.length && !window.confirm("병합하면 왼쪽 위 셀의 내용만 유지되고 나머지 셀 내용은 삭제됩니다. 계속할까요?")) return; if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds: discardedIds }) === false) return; const cells = { ...block.cells }; for (let row = range.startRow; row <= range.endRow; row++) for (let column = range.startColumn; column <= range.endColumn; column++) if (row !== range.startRow || column !== range.startColumn) delete cells[keyOf(row, column)]; commit({ ...block, cells, mergedRanges: [...block.mergedRanges, range] }); }
  function unmerge() { const removed = block.mergedRanges.filter((merged) => ranges.some((range) => rangesOverlap(merged, range))); const cells = { ...block.cells }; for (const merged of removed) { const value = normalize(merged); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) cells[keyOf(row, column)] ??= { id: crypto.randomUUID(), text: "" }; } commit({ ...block, cells, mergedRanges: block.mergedRanges.filter((merged) => !removed.includes(merged)) }); }
  function addRow(after: boolean) { const at = active.row + (after ? 1 : 0); commit(insertAxis(block, "row", at)); }
  function addColumn(after: boolean) { const at = active.column + (after ? 1 : 0); commit(insertAxis(block, "column", at)); }
  async function deleteAxis(axis: "row" | "column") { const indexes = new Set<number>(); for (const range of ranges) { const value = normalize(range); for (let index = axis === "row" ? value.startRow : value.startColumn; index <= (axis === "row" ? value.endRow : value.endColumn); index++) indexes.add(index); } if ((axis === "row" ? block.rows : block.columns) <= indexes.size) return window.alert("표에는 최소 한 개의 행과 열이 필요합니다."); const cellIds = Object.entries(block.cells).filter(([key]) => indexes.has(key.split(":").map(Number)[axis === "row" ? 0 : 1])).map(([, value]) => value.id); if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds }) === false) return; commit(removeAxis(block, axis, indexes)); setActive({ row: 0, column: 0 }); setRanges([{ startRow: 0, startColumn: 0, endRow: 0, endColumn: 0 }]); }
  useEffect(() => { const up = () => setDragging(false); window.addEventListener("pointerup", up); return () => window.removeEventListener("pointerup", up); }, []);
  const mergedLookup = useMemo(() => { const map = new Map<string, { range: TableRange; root: boolean }>(); for (const range of block.mergedRanges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) map.set(keyOf(row, column), { range: value, root: row === value.startRow && column === value.startColumn }); } return map; }, [block.mergedRanges]);
  return <div className="spreadsheet-shell" ref={root} tabIndex={0} onKeyDown={keyDown} onPaste={(event) => { if (!editing) { event.preventDefault(); pasteText(event.clipboardData.getData("text/plain")); } }}>
    <div className="sheet-toolbar"><button onClick={() => mutateSelected({ bold: true })} title="굵게"><Bold size={14}/></button><button onClick={() => mutateSelected({ italic: true })} title="기울임"><Italic size={14}/></button><button onClick={() => mutateSelected({ highlight: "#594f24" })} title="배경색"><Highlighter size={14}/></button><label title="글자색"><input type="color" onChange={(event) => mutateSelected({ textColor: event.target.value })}/></label><button onClick={() => mutateSelected({ horizontal: "left" })}><AlignLeft size={14}/></button><button onClick={() => mutateSelected({ horizontal: "center" })}><AlignCenter size={14}/></button><button onClick={() => mutateSelected({ horizontal: "right" })}><AlignRight size={14}/></button><button onClick={() => mutateSelected({ vertical: "top" })}>위</button><button onClick={() => mutateSelected({ vertical: "middle" })}>중앙</button><button onClick={() => mutateSelected({ vertical: "bottom" })}>아래</button><button onClick={() => mutateSelected({ wrap: true })}><WrapText size={14}/></button><button onClick={() => void merge()}><Merge size={14}/> 병합</button><button onClick={unmerge}><SplitSquareHorizontal size={14}/> 해제</button><button onClick={() => addRow(false)}><Rows3 size={14}/> 위 행</button><button onClick={() => addRow(true)}>아래 행</button><button onClick={() => addColumn(false)}><Columns3 size={14}/> 왼쪽 열</button><button onClick={() => addColumn(true)}>오른쪽 열</button><button onClick={() => void deleteAxis("row")}><Trash2 size={13}/> 행</button><button onClick={() => void deleteAxis("column")}><Trash2 size={13}/> 열</button></div>
    <div className="sheet-grid" style={{ gridTemplateColumns: `42px ${block.columnSizes.slice(0, block.columns).map((size) => `${size}px`).join(" ")}` }}>
      <button className="sheet-corner" onClick={() => { const range = { startRow: 0, startColumn: 0, endRow: block.rows - 1, endColumn: block.columns - 1 }; setRanges([range]); setAnchor({ row: 0, column: 0 }); }}/>{Array.from({ length: block.columns }, (_, column) => <button className="sheet-column-header" key={column} onClick={(event) => { const range = { startRow: 0, startColumn: column, endRow: block.rows - 1, endColumn: column }; setRanges(event.metaKey || event.ctrlKey ? [...ranges, range] : [range]); setActive({ row: 0, column }); setAnchor({ row: 0, column }); }}>{columnLabel(column)}<span onPointerDown={(event) => resizeAxis(event, block.columnSizes[column] ?? 128, (size) => { const sizes = [...block.columnSizes]; sizes[column] = size; onChange({ ...block, columnSizes: sizes }); })}/></button>)}
      {Array.from({ length: block.rows }, (_, row) => <div className="sheet-row-fragment" key={row} style={{ display: "contents" }}><button className="sheet-row-header" style={{ height: block.rowSizes[row] ?? 34 }} onClick={(event) => { const range = { startRow: row, startColumn: 0, endRow: row, endColumn: block.columns - 1 }; setRanges(event.metaKey || event.ctrlKey ? [...ranges, range] : [range]); setActive({ row, column: 0 }); setAnchor({ row, column: 0 }); }}>{row + 1}<span onPointerDown={(event) => resizeAxis(event, block.rowSizes[row] ?? 34, (size) => { const sizes = [...block.rowSizes]; sizes[row] = size; onChange({ ...block, rowSizes: sizes }); }, true)}/></button>{Array.from({ length: block.columns }, (_, column) => { const merged = mergedLookup.get(keyOf(row, column)); if (merged && !merged.root) return null; const value = cell(row, column); const target: ConceptTarget = { ownerType: "collection", ownerId: collectionId, targetType: editing?.row === row && editing.column === column ? "table_cell_text" : "table_cell", targetRef: { blockId: block.id, cellId: value.id } }; return <div key={column} {...conceptTargetAttributes(target)} data-cell={`${row}:${column}`} tabIndex={-1} className={`sheet-cell ${selected(row, column) ? "selected" : ""} ${active.row === row && active.column === column ? "active" : ""} ${clipboardRange && includes(clipboardRange, row, column) ? "copied" : ""}`} style={{ height: block.rowSizes[row] ?? 34, gridColumn: merged ? `span ${merged.range.endColumn - merged.range.startColumn + 1}` : undefined, gridRow: merged ? `span ${merged.range.endRow - merged.range.startRow + 1}` : undefined, fontWeight: value.bold ? 750 : undefined, fontStyle: value.italic ? "italic" : undefined, backgroundColor: value.highlight, color: value.textColor, textAlign: value.horizontal, alignItems: ({ top: "start", middle: "center", bottom: "end" } as const)[value.vertical ?? "top"], whiteSpace: value.wrap ? "pre-wrap" : "nowrap" }} onPointerDown={(event) => { if (editing) return; setDragging(true); select({ row, column }, event.shiftKey, event.metaKey || event.ctrlKey); }} onPointerEnter={() => { if (dragging) select({ row, column }, true, false); }} onDoubleClick={() => setEditing({ row, column })} onContextMenu={(event) => concepts?.openMenu(event, target, value.text)}>{editing?.row === row && editing.column === column ? <CellEditor value={value} target={target} shortcuts={shortcuts} onChange={(patch) => updateCell(row, column, patch)} onDone={() => setEditing(undefined)}/> : <span dangerouslySetInnerHTML={{ __html: value.html || escapeHtml(value.text) }}/>}</div>; })}</div>)}
    </div>
  </div>;
});

function CellEditor({ value, target, shortcuts, onChange, onDone }: { value: TableCell; target: ConceptTarget; shortcuts: import("@/lib/latex-shortcuts").LatexShortcut[]; onChange: (patch: Partial<TableCell>) => void; onDone: () => void }) { const ref = useRef<HTMLDivElement>(null); const composing = useRef(false); const concepts = useConceptEngine(); useEffect(() => { const node = ref.current; if (node) { node.innerHTML = value.html || escapeHtml(value.text); node.focus(); }  // Mount-only initialization avoids resetting the caret on every keystroke.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); function emit(includeEnd = false) { const node = ref.current; if (!node) return; normalizeTextNodes(node, shortcuts, includeEnd); const text = node.innerText; if (concepts?.reconcileText(target, value.text, text) === false) { node.innerHTML = value.html || escapeHtml(value.text); return; } onChange({ text, html: node.innerHTML }); } function command(name: string, commandValue?: string) { document.execCommand("styleWithCSS", false, "true"); document.execCommand(name, false, commandValue); emit(); } return <div className="sheet-cell-edit-wrap"><div className="sheet-cell-format"><button onMouseDown={(event) => event.preventDefault()} onClick={() => command("bold")}><Bold size={11}/></button><button onMouseDown={(event) => event.preventDefault()} onClick={() => command("italic")}><Italic size={11}/></button><button onMouseDown={(event) => event.preventDefault()} onClick={() => command("hiliteColor", "#594f24")}><Highlighter size={11}/></button><input type="color" onMouseDown={(event) => event.preventDefault()} onChange={(event) => command("foreColor", event.target.value)}/></div><div ref={ref} className="sheet-cell-editor" contentEditable suppressContentEditableWarning onCompositionStart={() => { composing.current = true; }} onCompositionEnd={() => { composing.current = false; emit(); }} onInput={() => { if (!composing.current) emit(); }} onBlur={() => { emit(true); onDone(); }} onKeyDown={(event) => { if (event.nativeEvent.isComposing) return; if ((event.metaKey || event.ctrlKey) && ["b", "i"].includes(event.key.toLowerCase())) { event.preventDefault(); command(event.key.toLowerCase() === "b" ? "bold" : "italic"); } }}/></div>; }
function fillSizes(values: number[], length: number, fallback: number) { return Array.from({ length }, (_, index) => values[index] ?? fallback); }
function columnLabel(index: number) { let value = index + 1; let label = ""; while (value) { value--; label = String.fromCharCode(65 + value % 26) + label; value = Math.floor(value / 26); } return label; }
function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function rangesOverlap(a: TableRange, b: TableRange) { const x = normalize(a), y = normalize(b); return x.startRow <= y.endRow && x.endRow >= y.startRow && x.startColumn <= y.endColumn && x.endColumn >= y.startColumn; }
function resizeAxis(event: React.PointerEvent, initial: number, onChange: (size: number) => void, vertical = false) { event.preventDefault(); event.stopPropagation(); const start = vertical ? event.clientY : event.clientX; const move = (pointer: PointerEvent) => onChange(Math.max(vertical ? 24 : 48, initial + (vertical ? pointer.clientY : pointer.clientX) - start)); const end = () => window.removeEventListener("pointermove", move); window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }
function insertAxis(block: CollectionTableBlock, axis: "row" | "column", at: number) { const cells: Record<string, TableCell> = {}; for (const [key, cell] of Object.entries(block.cells)) { const [row, column] = key.split(":").map(Number); cells[keyOf(axis === "row" && row >= at ? row + 1 : row, axis === "column" && column >= at ? column + 1 : column)] = cell; } if (axis === "row") for (let column = 0; column < block.columns; column++) cells[keyOf(at, column)] = { id: crypto.randomUUID(), text: "" }; else for (let row = 0; row < block.rows; row++) cells[keyOf(row, at)] = { id: crypto.randomUUID(), text: "" }; return { ...block, rows: block.rows + (axis === "row" ? 1 : 0), columns: block.columns + (axis === "column" ? 1 : 0), cells, rowSizes: axis === "row" ? [...block.rowSizes.slice(0, at), 34, ...block.rowSizes.slice(at)] : block.rowSizes, columnSizes: axis === "column" ? [...block.columnSizes.slice(0, at), 128, ...block.columnSizes.slice(at)] : block.columnSizes, mergedRanges: block.mergedRanges.map((range) => axis === "row" ? { ...range, startRow: range.startRow >= at ? range.startRow + 1 : range.startRow, endRow: range.endRow >= at ? range.endRow + 1 : range.endRow } : { ...range, startColumn: range.startColumn >= at ? range.startColumn + 1 : range.startColumn, endColumn: range.endColumn >= at ? range.endColumn + 1 : range.endColumn }) }; }
function removeAxis(block: CollectionTableBlock, axis: "row" | "column", indexes: Set<number>) { const cells: Record<string, TableCell> = {}; const shift = (index: number) => index - [...indexes].filter((removed) => removed < index).length; for (const [key, cell] of Object.entries(block.cells)) { const [row, column] = key.split(":").map(Number); if (indexes.has(axis === "row" ? row : column)) continue; cells[keyOf(axis === "row" ? shift(row) : row, axis === "column" ? shift(column) : column)] = cell; } return { ...block, rows: block.rows - (axis === "row" ? indexes.size : 0), columns: block.columns - (axis === "column" ? indexes.size : 0), cells, rowSizes: axis === "row" ? block.rowSizes.filter((_, index) => !indexes.has(index)) : block.rowSizes, columnSizes: axis === "column" ? block.columnSizes.filter((_, index) => !indexes.has(index)) : block.columnSizes, mergedRanges: [] }; }
function normalizeTextNodes(root: HTMLElement, shortcuts: import("@/lib/latex-shortcuts").LatexShortcut[], includeEnd: boolean) { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); while (walker.nextNode()) { const node = walker.currentNode as Text; node.data = applyLatexShortcuts(node.data, includeEnd, shortcuts); } }
