"use client";

import { AlignCenter, AlignLeft, AlignRight, Bold, ClipboardPaste, Columns3, Copy, Eraser, Highlighter, Italic, Merge, Minus, Plus, Redo2, Rows3, Scissors, SplitSquareHorizontal, Strikethrough, Trash2, Undo2, WrapText } from "lucide-react";
import { memo, useEffect, useMemo, useRef, useState } from "react";
import type { CollectionTableBlock, TableCell, TableRange } from "@/lib/db/schema";
import { conceptTargetAttributes, type ConceptTarget, useConceptEngine } from "@/components/concept-engine";
import { useLatexShortcuts } from "@/components/use-latex-shortcuts";
import { applyLatexShortcuts } from "@/lib/latex-shortcuts";

declare global { interface Event { readonly isComposing: boolean } }

type Position = { row: number; column: number };
type EditingState = Position & { initialText?: string };
type DragSession = { start: Position; baseRanges: TableRange[] };
type SelectionKind = "cells" | "rows" | "columns" | "all";
type EditorSize = { width?: number; height: number };
type Props = { block: CollectionTableBlock; collectionId: string; onChange: (block: CollectionTableBlock) => void };
const keyOf = (row: number, column: number) => `${row}:${column}`;
const normalize = (range: TableRange): TableRange => ({ startRow: Math.min(range.startRow, range.endRow), endRow: Math.max(range.startRow, range.endRow), startColumn: Math.min(range.startColumn, range.endColumn), endColumn: Math.max(range.startColumn, range.endColumn) });
const includes = (range: TableRange, row: number, column: number) => { const value = normalize(range); return row >= value.startRow && row <= value.endRow && column >= value.startColumn && column <= value.endColumn; };

export const SpreadsheetBlock = memo(function SpreadsheetBlock({ block, collectionId, onChange }: Props) {
  const [active, setActive] = useState<Position>({ row: 0, column: 0 }); const [anchor, setAnchor] = useState(active); const [ranges, setRanges] = useState<TableRange[]>([{ startRow: 0, startColumn: 0, endRow: 0, endColumn: 0 }]); const [selectionKind, setSelectionKind] = useState<SelectionKind>("cells"); const [editing, setEditing] = useState<EditingState>(); const [clipboardRange, setClipboardRange] = useState<TableRange>(); const [historyVersion, setHistoryVersion] = useState(0); const [formulaDraft, setFormulaDraft] = useState(""); const [editorSize, setEditorSize] = useState<EditorSize>({ height: 320 }); const [zoom, setZoom] = useState(100); const undo = useRef<CollectionTableBlock[]>([]); const redo = useRef<CollectionTableBlock[]>([]); const dragSession = useRef<DragSession | undefined>(undefined); const formulaCancelled = useRef(false); const formulaComposing = useRef(false); const internalClipboard = useRef<{ text: string; rows: TableCell[][] } | undefined>(undefined); const root = useRef<HTMLDivElement>(null); const gridScroll = useRef<HTMLDivElement>(null); const concepts = useConceptEngine();
  const editorSizeKey = `spreadsheet-editor-size:${collectionId}:${block.id}`;
  const zoomKey = `spreadsheet-zoom:${collectionId}:${block.id}`;
  const shortcuts = useLatexShortcuts();
  function remember(snapshot: CollectionTableBlock) { undo.current.push(structuredClone(snapshot)); if (undo.current.length > 50) undo.current.shift(); redo.current = []; setHistoryVersion((value) => value + 1); }
  const commit = (next: CollectionTableBlock, record = true) => { if (record) remember(block); onChange(next); };
  const cell = (row: number, column: number) => block.cells[keyOf(row, column)] ?? { id: crypto.randomUUID(), text: "" };
  const updateCell = (row: number, column: number, patch: Partial<TableCell>) => commit({ ...block, cells: { ...block.cells, [keyOf(row, column)]: { ...cell(row, column), ...patch } } });
  const selected = (row: number, column: number) => ranges.some((range) => includes(range, row, column));
  const canonicalPosition = (row: number, column: number) => { const merged = block.mergedRanges.find((range) => includes(range, row, column)); return merged ? { row: normalize(merged).startRow, column: normalize(merged).startColumn } : { row, column }; };
  const selectedCells = () => { const values: TableCell[] = []; const visited = new Set<string>(); for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) { const position = canonicalPosition(row, column); const key = keyOf(position.row, position.column); if (!visited.has(key)) { visited.add(key); values.push(cell(position.row, position.column)); } } } return values; };
  const allSelected = <K extends keyof TableCell,>(key: K, value: TableCell[K]) => { const cells = selectedCells(); return cells.length > 0 && cells.every((item) => { const actual = item[key] ?? (key === "horizontal" ? "left" : key === "vertical" ? "middle" : false); return actual === value; }); };
  const toggleSelected = (key: "bold" | "italic" | "strikethrough" | "wrap") => mutateSelected({ [key]: !allSelected(key, true) });
  function select(position: Position, extend: boolean, additive: boolean) { setSelectionKind("cells"); setActive(position); if (extend) { const range = { startRow: anchor.row, startColumn: anchor.column, endRow: position.row, endColumn: position.column }; setRanges((current) => additive ? [...current.slice(0, -1), range] : [range]); } else { setAnchor(position); const range = { startRow: position.row, startColumn: position.column, endRow: position.row, endColumn: position.column }; setRanges((current) => additive ? [...current, range] : [range]); } }
  function beginCellDrag(position: Position, event: React.PointerEvent) { const target = canonicalPosition(position.row, position.column); const additive = event.metaKey || event.ctrlKey; const start = event.shiftKey ? anchor : target; const baseRanges = additive ? [...ranges] : []; dragSession.current = { start, baseRanges }; setSelectionKind("cells"); setActive(target); if (!event.shiftKey) setAnchor(target); setRanges([...baseRanges, { startRow: start.row, startColumn: start.column, endRow: target.row, endColumn: target.column }]); root.current?.focus({ preventScroll: true }); }
  function continueCellDrag(position: Position) { const session = dragSession.current; if (!session) return; const target = canonicalPosition(position.row, position.column); setActive(target); setRanges([...session.baseRanges, { startRow: session.start.row, startColumn: session.start.column, endRow: target.row, endColumn: target.column }]); }
  function mutateSelected(patch: Partial<TableCell>) { const cells = { ...block.cells }; const visited = new Set<string>(); for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) { const position = canonicalPosition(row, column); const key = keyOf(position.row, position.column); if (!visited.has(key)) { visited.add(key); cells[key] = { ...cell(position.row, position.column), ...patch }; } } } commit({ ...block, cells }); }
  function clearFormatting() { const cells = { ...block.cells }; const visited = new Set<string>(); for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) { const position = canonicalPosition(row, column); const key = keyOf(position.row, position.column); if (visited.has(key)) continue; visited.add(key); const current = cell(position.row, position.column); cells[key] = { id: current.id, text: current.text, html: escapeHtml(current.text) }; } } commit({ ...block, cells }); }
  async function clearSelected() { const cells = { ...block.cells }; const cellIds: string[] = []; const visited = new Set<string>(); for (const range of ranges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) { const position = canonicalPosition(row, column); const key = keyOf(position.row, position.column); if (visited.has(key)) continue; visited.add(key); cellIds.push(cell(position.row, position.column).id); cells[key] = { ...cell(position.row, position.column), text: "", html: "" }; } } if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds }) === false) return; commit({ ...block, cells }); }
  async function copy() { const rows: TableCell[][] = []; for (const [rangeIndex, item] of ranges.entries()) { const range = normalize(item); if (rangeIndex) rows.push([]); for (let row = range.startRow; row <= range.endRow; row++) rows.push(Array.from({ length: range.endColumn - range.startColumn + 1 }, (_, offset) => structuredClone(cell(row, range.startColumn + offset)))); } const text = rows.map((row) => row.map((value) => value.text).join("\t")).join("\n"); internalClipboard.current = { text, rows }; await navigator.clipboard.writeText(text); setClipboardRange(ranges.length === 1 ? normalize(ranges[0]) : undefined); }
  async function cut() { await copy(); await clearSelected(); }
  async function pasteFromClipboard() { try { pasteText(await navigator.clipboard.readText()); } catch { window.alert("클립보드를 읽을 수 없습니다. Cmd/Ctrl+V를 사용하세요."); } }
  function pasteText(text: string) { const grid = text.replace(/\r/g, "").split("\n").map((row) => row.split("\t")); const rows = Math.max(block.rows, active.row + grid.length); const columns = Math.max(block.columns, active.column + Math.max(...grid.map((row) => row.length))); const cells = { ...block.cells }; const internal = internalClipboard.current?.text === text ? internalClipboard.current.rows : undefined; for (let row = 0; row < rows; row++) for (let column = 0; column < columns; column++) cells[keyOf(row, column)] ??= { id: crypto.randomUUID(), text: "" }; grid.forEach((values, row) => values.forEach((textValue, column) => { const position = keyOf(active.row + row, active.column + column); const style = internal?.[row]?.[column]; cells[position] = { ...cells[position], ...(style ? { ...style, id: cells[position].id } : {}), text: textValue, html: style?.html ?? escapeHtml(textValue) }; })); commit({ ...block, rows, columns, cells, rowSizes: fillSizes(block.rowSizes, rows, 34), columnSizes: fillSizes(block.columnSizes, columns, 128) }); }
  function move(rowDelta: number, columnDelta: number, extend: boolean) { const position = { row: Math.max(0, Math.min(block.rows - 1, active.row + rowDelta)), column: Math.max(0, Math.min(block.columns - 1, active.column + columnDelta)) }; select(position, extend, false); requestAnimationFrame(() => root.current?.querySelector<HTMLElement>(`[data-cell="${position.row}:${position.column}"]`)?.focus()); }
  function history(direction: "undo" | "redo") { const from = direction === "undo" ? undo : redo; const to = direction === "undo" ? redo : undo; const previous = from.current.pop(); if (!previous) return; to.current.push(structuredClone(block)); onChange(previous); setHistoryVersion((value) => value + 1); }
  function setSheetZoom(value: number) { const next = Math.max(50, Math.min(200, Math.round(value / 10) * 10)); setZoom(next); window.localStorage.setItem(zoomKey, String(next)); }
  function normalizeFormulaInput(node: HTMLTextAreaElement, includeEnd = false) {
    const before = node.value;
    const start = node.selectionStart;
    const end = node.selectionEnd;
    const normalized = applyLatexShortcuts(before, includeEnd, shortcuts);
    setFormulaDraft(normalized);
    if (normalized === before) return;
    const nextStart = applyLatexShortcuts(before.slice(0, start), includeEnd, shortcuts).length;
    const nextEnd = applyLatexShortcuts(before.slice(0, end), includeEnd, shortcuts).length;
    requestAnimationFrame(() => node.setSelectionRange(nextStart, nextEnd));
  }
  // Cmd/Ctrl+M unmerges only when every selected rectangle is an existing merge;
  // otherwise it attempts one atomic merge operation for all selected rectangles.
  function toggleMerge() { const meaningful = ranges.map(normalize).filter((range) => !singleCell(range)); if (meaningful.length && meaningful.every((range) => block.mergedRanges.some((merged) => sameRange(merged, range)))) unmerge(); else void merge(); }
  function keyDown(event: React.KeyboardEvent) { if (editing) return; const command = event.metaKey || event.ctrlKey; const key = event.key.toLowerCase(); if (command && key === "s") return; if (command && (key === "+" || key === "=")) { event.preventDefault(); event.stopPropagation(); setSheetZoom(zoom + 10); return; } if (command && key === "-") { event.preventDefault(); event.stopPropagation(); setSheetZoom(zoom - 10); return; } if (command && key === "0") { event.preventDefault(); event.stopPropagation(); setSheetZoom(100); return; } if (command && key === "c") { event.preventDefault(); void copy(); return; } if (command && key === "x") { event.preventDefault(); void cut(); return; } if (command && key === "v") { event.preventDefault(); void pasteFromClipboard(); return; } if (command && key === "b") { event.preventDefault(); toggleSelected("bold"); return; } if (command && key === "i") { event.preventDefault(); toggleSelected("italic"); return; } if (command && key === "z") { event.preventDefault(); event.stopPropagation(); history(event.shiftKey ? "redo" : "undo"); return; } if (command && key === "y") { event.preventDefault(); event.stopPropagation(); history("redo"); return; } if (command && key === "m") { event.preventDefault(); event.stopPropagation(); toggleMerge(); return; } if (event.key === "Escape") { setClipboardRange(undefined); return; } if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); void clearSelected(); return; } const movements: Record<string, [number, number]> = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1], Tab: [0, event.shiftKey ? -1 : 1], Enter: [event.shiftKey ? -1 : 1, 0] }; const movement = movements[event.key]; if (movement) { event.preventDefault(); move(movement[0], movement[1], event.shiftKey && event.key.startsWith("Arrow")); return; } const target = canonicalPosition(active.row, active.column); if (!command && !event.altKey && (event.nativeEvent.isComposing || event.key === "Process" || event.key === "Unidentified")) { setEditing({ ...target, initialText: "" }); return; } if (!command && !event.altKey && event.key.length === 1) { event.preventDefault(); setEditing({ ...target, initialText: event.key }); } }
  async function merge() { const targets = ranges.map(normalize).filter((range) => !singleCell(range)); if (!targets.length) return; const selectedOverlap = targets.some((range, index) => targets.slice(index + 1).some((other) => rangesOverlap(range, other))); if (selectedOverlap || targets.some((range) => block.mergedRanges.some((merged) => rangesOverlap(merged, range)))) return window.alert("선택 범위끼리 겹치거나 기존 병합 셀과 겹칩니다. 병합을 먼저 해제해 주세요."); const discardedIds: string[] = []; let hasDiscardedContent = false; for (const range of targets) for (let row = range.startRow; row <= range.endRow; row++) for (let column = range.startColumn; column <= range.endColumn; column++) if (row !== range.startRow || column !== range.startColumn) { discardedIds.push(cell(row, column).id); if (cell(row, column).text) hasDiscardedContent = true; } if (hasDiscardedContent && !window.confirm("병합하면 각 선택 범위에서 왼쪽 위 셀의 내용만 유지되고 나머지 셀 내용은 삭제됩니다.")) return; if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds: discardedIds }) === false) return; const cells = { ...block.cells }; for (const range of targets) { for (let row = range.startRow; row <= range.endRow; row++) for (let column = range.startColumn; column <= range.endColumn; column++) if (row !== range.startRow || column !== range.startColumn) delete cells[keyOf(row, column)]; const rootKey = keyOf(range.startRow, range.startColumn); cells[rootKey] = { ...cells[rootKey], horizontal: "center", vertical: "middle" }; } commit({ ...block, cells, mergedRanges: [...block.mergedRanges, ...targets] }); setRanges(targets); setActive({ row: targets[0].startRow, column: targets[0].startColumn }); }
  function unmerge() { const removed = block.mergedRanges.filter((merged) => ranges.some((range) => rangesOverlap(merged, range))); if (!removed.length) return; const cells = { ...block.cells }; for (const merged of removed) { const value = normalize(merged); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) cells[keyOf(row, column)] ??= { id: crypto.randomUUID(), text: "" }; } commit({ ...block, cells, mergedRanges: block.mergedRanges.filter((merged) => !removed.includes(merged)) }); }
  function insertSelectedAxis() { if (selectionKind !== "rows" && selectionKind !== "columns") return; const axis = selectionKind === "rows" ? "row" : "column"; const indexes = selectedAxisIndexes(ranges, axis); const at = Math.min(...indexes); let next = block; for (let count = 0; count < indexes.length; count++) next = insertAxis(next, axis, at); commit(next); if (axis === "row") { setRanges([{ startRow: at, endRow: at + indexes.length - 1, startColumn: 0, endColumn: next.columns - 1 }]); setActive({ row: at, column: 0 }); } else { setRanges([{ startRow: 0, endRow: next.rows - 1, startColumn: at, endColumn: at + indexes.length - 1 }]); setActive({ row: 0, column: at }); } }
  function resizeGridAxis(event: React.PointerEvent, axis: "row" | "column", index: number) { const before = structuredClone(block); const initial = axis === "row" ? block.rowSizes[index] ?? 34 : block.columnSizes[index] ?? 128; resizeAxis(event, initial * zoom / 100, (renderedSize) => { const size = renderedSize * 100 / zoom; if (axis === "row") { const rowSizes = [...before.rowSizes]; rowSizes[index] = size; onChange({ ...before, rowSizes }); } else { const columnSizes = [...before.columnSizes]; columnSizes[index] = size; onChange({ ...before, columnSizes }); } }, axis === "row", () => remember(before), zoom / 100); }
  function beginEditorResize(event: React.PointerEvent, axis: "width" | "height" | "both") { event.preventDefault(); event.stopPropagation(); const startX = event.clientX; const startY = event.clientY; const startWidth = root.current?.getBoundingClientRect().width ?? 720; const startHeight = gridScroll.current?.getBoundingClientRect().height ?? editorSize.height; let latest: EditorSize = { width: editorSize.width ?? startWidth, height: editorSize.height }; const move = (pointer: PointerEvent) => { latest = { width: axis === "height" ? latest.width : Math.max(480, Math.min(3200, startWidth + pointer.clientX - startX)), height: axis === "width" ? latest.height : Math.max(180, Math.min(1800, startHeight + pointer.clientY - startY)) }; setEditorSize(latest); }; const end = () => { window.removeEventListener("pointermove", move); window.localStorage.setItem(editorSizeKey, JSON.stringify(latest)); document.body.classList.remove("resizing-spreadsheet"); }; document.body.classList.add("resizing-spreadsheet"); window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }
  async function deleteAxis(axis: "row" | "column") { const indexes = new Set<number>(); for (const range of ranges) { const value = normalize(range); for (let index = axis === "row" ? value.startRow : value.startColumn; index <= (axis === "row" ? value.endRow : value.endColumn); index++) indexes.add(index); } if ((axis === "row" ? block.rows : block.columns) <= indexes.size) return window.alert("표에는 최소 한 개의 행과 열이 필요합니다."); const cellIds = Object.entries(block.cells).filter(([key]) => indexes.has(key.split(":").map(Number)[axis === "row" ? 0 : 1])).map(([, value]) => value.id); if (await concepts?.breakAnchors({ ownerId: collectionId, blockIds: [block.id], cellIds }) === false) return; commit(removeAxis(block, axis, indexes)); setActive({ row: 0, column: 0 }); setRanges([{ startRow: 0, startColumn: 0, endRow: 0, endColumn: 0 }]); }
  useEffect(() => { const up = () => { dragSession.current = undefined; }; window.addEventListener("pointerup", up); window.addEventListener("pointercancel", up); return () => { window.removeEventListener("pointerup", up); window.removeEventListener("pointercancel", up); }; }, []);
  useEffect(() => { try { const stored = JSON.parse(window.localStorage.getItem(editorSizeKey) ?? "null") as Partial<EditorSize> | null; if (stored && (stored.width || stored.height)) setEditorSize({ width: stored.width && stored.width >= 480 ? stored.width : undefined, height: stored.height && stored.height >= 180 ? stored.height : 320 }); } catch { /* Ignore a malformed local preference. */ } }, [editorSizeKey]);
  useEffect(() => { const stored = Number(window.localStorage.getItem(zoomKey)); if (stored >= 50 && stored <= 200) setZoom(stored); }, [zoomKey]);
  useEffect(() => { setFormulaDraft(block.cells[keyOf(active.row, active.column)]?.text ?? ""); }, [active.row, active.column, block.cells]);
  const mergedLookup = useMemo(() => { const map = new Map<string, { range: TableRange; root: boolean }>(); for (const range of block.mergedRanges) { const value = normalize(range); for (let row = value.startRow; row <= value.endRow; row++) for (let column = value.startColumn; column <= value.endColumn; column++) map.set(keyOf(row, column), { range: value, root: row === value.startRow && column === value.startColumn }); } return map; }, [block.mergedRanges]);
  const selectionLabel = ranges.map((item) => { const range = normalize(item); const start = `${columnLabel(range.startColumn)}${range.startRow + 1}`; const end = `${columnLabel(range.endColumn)}${range.endRow + 1}`; return start === end ? start : `${start}:${end}`; }).join(", ");
  const scale = zoom / 100;
  return <div className="spreadsheet-shell" ref={root} style={{ width: editorSize.width ? `${editorSize.width}px` : "100%" }} tabIndex={0} onKeyDown={keyDown} onBeforeInput={(event) => { if (editing) return; const input = event.nativeEvent as InputEvent; if (!input.isComposing || !input.data) return; event.preventDefault(); const target = canonicalPosition(active.row, active.column); setEditing({ ...target, initialText: input.data }); }} onPaste={(event) => { if (!editing) { event.preventDefault(); pasteText(event.clipboardData.getData("text/plain")); } }}>
    <div className="sheet-toolbar" aria-label="표 편집 도구" onPointerDown={(event) => { if ((event.target as HTMLElement).closest("button")) event.preventDefault(); }}>
      <div className="sheet-tool-group"><button onClick={() => history("undo")} disabled={!undo.current.length} title="실행 취소 (Cmd/Ctrl+Z)"><Undo2 size={14}/></button><button onClick={() => history("redo")} disabled={!redo.current.length} title="다시 실행 (Cmd/Ctrl+Shift+Z)" data-history-version={historyVersion}><Redo2 size={14}/></button></div>
      <div className="sheet-tool-group"><button onClick={() => void cut()} title="잘라내기 (Cmd/Ctrl+X)"><Scissors size={14}/></button><button onClick={() => void copy()} title="복사 (Cmd/Ctrl+C)"><Copy size={14}/></button><button onClick={() => void pasteFromClipboard()} title="붙여넣기 (Cmd/Ctrl+V)"><ClipboardPaste size={14}/></button></div>
      <div className="sheet-tool-group"><button className={allSelected("bold", true) ? "active" : ""} onClick={() => toggleSelected("bold")} title="굵게"><Bold size={14}/></button><button className={allSelected("italic", true) ? "active" : ""} onClick={() => toggleSelected("italic")} title="기울임"><Italic size={14}/></button><button className={allSelected("strikethrough", true) ? "active" : ""} onClick={() => toggleSelected("strikethrough")} title="취소선"><Strikethrough size={14}/></button><label className="sheet-color-tool" title="글자색"><span>A</span><input type="color" defaultValue="#dfe3e8" onChange={(event) => mutateSelected({ textColor: event.target.value })}/></label><label className="sheet-color-tool" title="채우기 색"><Highlighter size={14}/><input type="color" defaultValue="#594f24" onChange={(event) => mutateSelected({ highlight: event.target.value })}/></label><button onClick={clearFormatting} title="서식 지우기"><Eraser size={14}/></button></div>
      <div className="sheet-tool-group"><button className={allSelected("horizontal", "left") ? "active" : ""} onClick={() => mutateSelected({ horizontal: "left" })} title="왼쪽 정렬"><AlignLeft size={14}/></button><button className={allSelected("horizontal", "center") ? "active" : ""} onClick={() => mutateSelected({ horizontal: "center" })} title="가운데 정렬"><AlignCenter size={14}/></button><button className={allSelected("horizontal", "right") ? "active" : ""} onClick={() => mutateSelected({ horizontal: "right" })} title="오른쪽 정렬"><AlignRight size={14}/></button><button className={allSelected("vertical", "top") ? "active" : ""} onClick={() => mutateSelected({ vertical: "top" })}>위</button><button className={allSelected("vertical", "middle") ? "active" : ""} onClick={() => mutateSelected({ vertical: "middle" })}>중앙</button><button className={allSelected("vertical", "bottom") ? "active" : ""} onClick={() => mutateSelected({ vertical: "bottom" })}>아래</button><button className={allSelected("wrap", true) ? "active" : ""} onClick={() => toggleSelected("wrap")} title="줄바꿈"><WrapText size={14}/></button></div>
      <div className="sheet-tool-group"><button onClick={() => void merge()}><Merge size={14}/> 병합</button><button onClick={unmerge}><SplitSquareHorizontal size={14}/> 해제</button></div>
      <div className="sheet-tool-group sheet-axis-tools"><button className="sheet-structure-button" disabled={selectionKind !== "rows" && selectionKind !== "columns"} onClick={insertSelectedAxis} title={selectionKind === "rows" ? "선택한 행 위에 행 삽입" : selectionKind === "columns" ? "선택한 열 왼쪽에 열 삽입" : "먼저 행 번호 또는 열 문자를 선택하세요"}><span className="sheet-structure-icon">{selectionKind === "columns" ? <Columns3 size={16}/> : <Rows3 size={16}/>}<Plus size={9}/></span><span>삽입</span></button><button className="sheet-structure-button" disabled={selectionKind !== "rows" && selectionKind !== "columns"} onClick={() => void deleteAxis(selectionKind === "rows" ? "row" : "column")} title={selectionKind === "rows" ? "선택한 행 삭제" : selectionKind === "columns" ? "선택한 열 삭제" : "먼저 행 번호 또는 열 문자를 선택하세요"}><span className="sheet-structure-icon">{selectionKind === "columns" ? <Columns3 size={16}/> : <Rows3 size={16}/>}<Trash2 size={9}/></span><span>삭제</span></button></div>
      <div className="sheet-tool-group sheet-zoom-tools"><button onClick={() => setSheetZoom(zoom - 10)} disabled={zoom <= 50} title="축소 (Cmd/Ctrl+-)"><Minus size={13}/></button><button onClick={() => setSheetZoom(100)} title="100%로 재설정 (Cmd/Ctrl+0)">{zoom}%</button><button onClick={() => setSheetZoom(zoom + 10)} disabled={zoom >= 200} title="확대 (Cmd/Ctrl++)"><Plus size={13}/></button></div>
    </div>
    <div className="sheet-formula-bar"><strong title={selectionLabel}>{selectionLabel}</strong><span>fx</span><textarea rows={1} style={{ fontSize: `${11 * scale}px` }} value={formulaDraft} onFocus={() => { formulaCancelled.current = false; }} onCompositionStart={() => { formulaComposing.current = true; }} onCompositionEnd={(event) => { formulaComposing.current = false; normalizeFormulaInput(event.currentTarget); }} onChange={(event) => { if (formulaComposing.current || event.nativeEvent.isComposing) setFormulaDraft(event.target.value); else normalizeFormulaInput(event.currentTarget); }} onBlur={() => { const normalized = applyLatexShortcuts(formulaDraft, true, shortcuts); if (!formulaCancelled.current && normalized !== cell(active.row, active.column).text) updateCell(active.row, active.column, { text: normalized, html: escapeHtml(normalized).replace(/\n/g, "<br>") }); formulaCancelled.current = false; }} onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "z") { event.stopPropagation(); return; } if (event.nativeEvent.isComposing) return; if (event.key === "Enter" && event.altKey) { event.preventDefault(); const node = event.currentTarget; const start = node.selectionStart; const next = `${formulaDraft.slice(0, start)}\n${formulaDraft.slice(node.selectionEnd)}`; setFormulaDraft(next); requestAnimationFrame(() => node.setSelectionRange(start + 1, start + 1)); return; } if (event.key === "Enter") { event.preventDefault(); event.currentTarget.blur(); } if (event.key === "Escape") { formulaCancelled.current = true; setFormulaDraft(cell(active.row, active.column).text); event.currentTarget.blur(); } }} aria-label="활성 셀 내용"/></div>
    <div className="sheet-grid-scroll" ref={gridScroll} style={{ height: `${editorSize.height}px` }}><div className="sheet-grid" style={{ fontSize: `${12 * scale}px`, gridTemplateColumns: `${42 * scale}px ${block.columnSizes.slice(0, block.columns).map((size) => `${size * scale}px`).join(" ")}`, gridTemplateRows: `${28 * scale}px ${block.rowSizes.slice(0, block.rows).map((size) => `${size * scale}px`).join(" ")}` }}>
      <button className="sheet-corner" style={{ gridColumn: 1, gridRow: 1 }} onClick={() => { const range = { startRow: 0, startColumn: 0, endRow: block.rows - 1, endColumn: block.columns - 1 }; setSelectionKind("all"); setRanges([range]); setAnchor({ row: 0, column: 0 }); }}/>{Array.from({ length: block.columns }, (_, column) => <button className="sheet-column-header" style={{ gridColumn: column + 2, gridRow: 1, height: `${28 * scale}px`, fontSize: `${10 * scale}px` }} key={column} onClick={(event) => { const range = { startRow: 0, startColumn: column, endRow: block.rows - 1, endColumn: column }; setSelectionKind("columns"); setRanges(event.metaKey || event.ctrlKey ? [...ranges, range] : [range]); setActive({ row: 0, column }); setAnchor({ row: 0, column }); root.current?.focus({ preventScroll: true }); }}>{columnLabel(column)}<span onPointerDown={(event) => resizeGridAxis(event, "column", column)}/></button>)}
      {Array.from({ length: block.rows }, (_, row) => <div className="sheet-row-fragment" key={row} style={{ display: "contents" }}><button className="sheet-row-header" style={{ gridColumn: 1, gridRow: row + 2, height: "100%", fontSize: `${10 * scale}px` }} onClick={(event) => { const range = { startRow: row, startColumn: 0, endRow: row, endColumn: block.columns - 1 }; setSelectionKind("rows"); setRanges(event.metaKey || event.ctrlKey ? [...ranges, range] : [range]); setActive({ row, column: 0 }); setAnchor({ row, column: 0 }); root.current?.focus({ preventScroll: true }); }}>{row + 1}<span onPointerDown={(event) => resizeGridAxis(event, "row", row)}/></button>{Array.from({ length: block.columns }, (_, column) => { const merged = mergedLookup.get(keyOf(row, column)); if (merged && !merged.root) return null; const value = cell(row, column); const target: ConceptTarget = { ownerType: "collection", ownerId: collectionId, targetType: editing?.row === row && editing.column === column ? "table_cell_text" : "table_cell", targetRef: { blockId: block.id, cellId: value.id } }; const rowSpan = merged ? merged.range.endRow - merged.range.startRow + 1 : 1; const columnSpan = merged ? merged.range.endColumn - merged.range.startColumn + 1 : 1; return <div key={column} {...conceptTargetAttributes(target)} data-cell={`${row}:${column}`} tabIndex={-1} className={`sheet-cell ${selected(row, column) ? "selected" : ""} ${active.row === row && active.column === column ? "active" : ""} ${clipboardRange && includes(clipboardRange, row, column) ? "copied" : ""}`} style={{ height: "100%", padding: `${5 * scale}px ${7 * scale}px`, gridColumn: `${column + 2} / span ${columnSpan}`, gridRow: `${row + 2} / span ${rowSpan}`, fontWeight: value.bold ? 750 : undefined, fontStyle: value.italic ? "italic" : undefined, textDecoration: value.strikethrough ? "line-through" : undefined, backgroundColor: value.highlight, color: value.textColor, textAlign: value.horizontal ?? "left", alignItems: ({ top: "flex-start", middle: "center", bottom: "flex-end" } as const)[value.vertical ?? "middle"], whiteSpace: value.wrap ? "pre-wrap" : "nowrap" }} onPointerDown={(event) => { if (editing) return; beginCellDrag({ row, column }, event); }} onPointerEnter={() => continueCellDrag({ row, column })} onDoubleClick={() => setEditing({ row, column })} onContextMenu={(event) => concepts?.openMenu(event, target, value.text)}>{editing?.row === row && editing.column === column ? <CellEditor value={value} initialText={editing.initialText} target={target} shortcuts={shortcuts} onChange={(patch) => updateCell(row, column, patch)} onDone={(advance) => { setEditing(undefined); if (advance) move(1, 0, false); else requestAnimationFrame(() => root.current?.focus({ preventScroll: true })); }}/> : <span dangerouslySetInnerHTML={{ __html: value.html || escapeHtml(value.text) }}/>}</div>; })}</div>)}
    </div></div><div className="sheet-resize-handle sheet-resize-right" onPointerDown={(event) => beginEditorResize(event, "width")} aria-hidden="true"/><div className="sheet-resize-handle sheet-resize-bottom" onPointerDown={(event) => beginEditorResize(event, "height")} aria-hidden="true"/><div className="sheet-resize-handle sheet-resize-corner" onPointerDown={(event) => beginEditorResize(event, "both")} aria-hidden="true"/>
  </div>;
});

function CellEditor({ value, initialText, target, shortcuts, onChange, onDone }: { value: TableCell; initialText?: string; target: ConceptTarget; shortcuts: import("@/lib/latex-shortcuts").LatexShortcut[]; onChange: (patch: Partial<TableCell>) => void; onDone: (advance: boolean) => void }) { const ref = useRef<HTMLDivElement>(null); const cancelled = useRef(false); const advance = useRef(false); const composing = useRef(false); const concepts = useConceptEngine(); useEffect(() => { const node = ref.current; if (node) { node.innerHTML = initialText === undefined ? value.html || escapeHtml(value.text) : escapeHtml(initialText); node.focus(); placeCaretAtEnd(node); }  // Mount-only initialization avoids resetting the caret on every keystroke.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); function normalizeEditing(includeEnd = false) { const node = ref.current; if (node) normalizeTextNodesAtCaret(node, shortcuts, includeEnd); } function commitEdit() { const node = ref.current; if (!node || cancelled.current) return; normalizeEditing(true); const text = node.innerText; if (concepts?.reconcileText(target, value.text, text) === false) { node.innerHTML = value.html || escapeHtml(value.text); return; } if (text !== value.text || node.innerHTML !== (value.html || escapeHtml(value.text))) onChange({ text, html: node.innerHTML }); } return <div className="sheet-cell-edit-wrap"><div ref={ref} className="sheet-cell-editor" contentEditable suppressContentEditableWarning onCompositionStart={() => { composing.current = true; }} onCompositionEnd={() => { composing.current = false; normalizeEditing(); }} onInput={(event) => { if (!composing.current && !event.nativeEvent.isComposing) normalizeEditing(); }} onBlur={() => { commitEdit(); onDone(advance.current && !cancelled.current); }} onKeyDown={(event) => { if (event.nativeEvent.isComposing || composing.current) return; if (event.key === "Escape") { event.preventDefault(); cancelled.current = true; ref.current!.innerHTML = value.html || escapeHtml(value.text); ref.current?.blur(); } else if (event.key === "Enter" && event.altKey) { event.preventDefault(); document.execCommand("insertLineBreak"); } else if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); advance.current = true; ref.current?.blur(); } }}/></div>; }
function fillSizes(values: number[], length: number, fallback: number) { return Array.from({ length }, (_, index) => values[index] ?? fallback); }
function columnLabel(index: number) { let value = index + 1; let label = ""; while (value) { value--; label = String.fromCharCode(65 + value % 26) + label; value = Math.floor(value / 26); } return label; }
function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function placeCaretAtEnd(node: HTMLElement) { const selection = window.getSelection(); if (!selection) return; const range = document.createRange(); range.selectNodeContents(node); range.collapse(false); selection.removeAllRanges(); selection.addRange(range); }
function rangesOverlap(a: TableRange, b: TableRange) { const x = normalize(a), y = normalize(b); return x.startRow <= y.endRow && x.endRow >= y.startRow && x.startColumn <= y.endColumn && x.endColumn >= y.startColumn; }
function sameRange(a: TableRange, b: TableRange) { const x = normalize(a), y = normalize(b); return x.startRow === y.startRow && x.endRow === y.endRow && x.startColumn === y.startColumn && x.endColumn === y.endColumn; }
function singleCell(range: TableRange) { const value = normalize(range); return value.startRow === value.endRow && value.startColumn === value.endColumn; }
function selectedAxisIndexes(ranges: TableRange[], axis: "row" | "column") { const indexes = new Set<number>(); for (const source of ranges) { const range = normalize(source); const start = axis === "row" ? range.startRow : range.startColumn; const end = axis === "row" ? range.endRow : range.endColumn; for (let index = start; index <= end; index++) indexes.add(index); } return [...indexes].sort((a, b) => a - b); }
function resizeAxis(event: React.PointerEvent, initial: number, onChange: (size: number) => void, vertical = false, onEnd?: () => void, scale = 1) { event.preventDefault(); event.stopPropagation(); const start = vertical ? event.clientY : event.clientX; let changed = false; const move = (pointer: PointerEvent) => { changed = true; onChange(Math.max((vertical ? 24 : 48) * scale, initial + (vertical ? pointer.clientY : pointer.clientX) - start)); }; const end = () => { window.removeEventListener("pointermove", move); if (changed) onEnd?.(); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }
function insertAxis(block: CollectionTableBlock, axis: "row" | "column", at: number) { const cells: Record<string, TableCell> = {}; for (const [key, cell] of Object.entries(block.cells)) { const [row, column] = key.split(":").map(Number); cells[keyOf(axis === "row" && row >= at ? row + 1 : row, axis === "column" && column >= at ? column + 1 : column)] = cell; } if (axis === "row") for (let column = 0; column < block.columns; column++) cells[keyOf(at, column)] = { id: crypto.randomUUID(), text: "" }; else for (let row = 0; row < block.rows; row++) cells[keyOf(row, at)] = { id: crypto.randomUUID(), text: "" }; return { ...block, rows: block.rows + (axis === "row" ? 1 : 0), columns: block.columns + (axis === "column" ? 1 : 0), cells, rowSizes: axis === "row" ? [...block.rowSizes.slice(0, at), 34, ...block.rowSizes.slice(at)] : block.rowSizes, columnSizes: axis === "column" ? [...block.columnSizes.slice(0, at), 128, ...block.columnSizes.slice(at)] : block.columnSizes, mergedRanges: block.mergedRanges.map((range) => axis === "row" ? { ...range, startRow: range.startRow >= at ? range.startRow + 1 : range.startRow, endRow: range.endRow >= at ? range.endRow + 1 : range.endRow } : { ...range, startColumn: range.startColumn >= at ? range.startColumn + 1 : range.startColumn, endColumn: range.endColumn >= at ? range.endColumn + 1 : range.endColumn }) }; }
function removeAxis(block: CollectionTableBlock, axis: "row" | "column", indexes: Set<number>) { const cells: Record<string, TableCell> = {}; const shift = (index: number) => index - [...indexes].filter((removed) => removed < index).length; for (const [key, cell] of Object.entries(block.cells)) { const [row, column] = key.split(":").map(Number); if (indexes.has(axis === "row" ? row : column)) continue; cells[keyOf(axis === "row" ? shift(row) : row, axis === "column" ? shift(column) : column)] = cell; } const mergedRanges = block.mergedRanges.flatMap((source) => { const range = normalize(source); const rows = Array.from({ length: range.endRow - range.startRow + 1 }, (_, offset) => range.startRow + offset).filter((index) => axis !== "row" || !indexes.has(index)).map((index) => axis === "row" ? shift(index) : index); const columns = Array.from({ length: range.endColumn - range.startColumn + 1 }, (_, offset) => range.startColumn + offset).filter((index) => axis !== "column" || !indexes.has(index)).map((index) => axis === "column" ? shift(index) : index); if (!rows.length || !columns.length || (rows.length === 1 && columns.length === 1)) return []; return [{ startRow: Math.min(...rows), endRow: Math.max(...rows), startColumn: Math.min(...columns), endColumn: Math.max(...columns) }]; }); return { ...block, rows: block.rows - (axis === "row" ? indexes.size : 0), columns: block.columns - (axis === "column" ? indexes.size : 0), cells, rowSizes: axis === "row" ? block.rowSizes.filter((_, index) => !indexes.has(index)) : block.rowSizes, columnSizes: axis === "column" ? block.columnSizes.filter((_, index) => !indexes.has(index)) : block.columnSizes, mergedRanges }; }
function normalizeTextNodesAtCaret(root: HTMLElement, shortcuts: import("@/lib/latex-shortcuts").LatexShortcut[], includeEnd: boolean) {
  const textNodes: Text[] = [];
  const initialWalker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  while (initialWalker.nextNode()) textNodes.push(initialWalker.currentNode as Text);
  if (!textNodes.some((node) => applyLatexShortcuts(node.data, includeEnd, shortcuts) !== node.data)) return;

  const selection = window.getSelection();
  const active = Boolean(selection?.rangeCount && selection.isCollapsed && root.contains(selection.anchorNode));
  const marker = active ? document.createElement("span") : undefined;
  if (marker && selection) {
    marker.dataset.sheetCaretMarker = "true";
    marker.setAttribute("contenteditable", "false");
    selection.getRangeAt(0).insertNode(marker);
  }

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    const normalized = applyLatexShortcuts(node.data, includeEnd, shortcuts);
    if (normalized !== node.data) node.data = normalized;
  }

  if (marker?.parentNode) {
    const parent = marker.parentNode;
    const offset = Array.prototype.indexOf.call(parent.childNodes, marker) as number;
    marker.remove();
    const range = document.createRange();
    range.setStart(parent, Math.min(offset, parent.childNodes.length));
    range.collapse(true);
    selection?.removeAllRanges();
    selection?.addRange(range);
  }
}
