"use client";
/* eslint-disable @next/next/no-img-element -- private Blob media is streamed through the application route */
import { Images, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
type Data = { stats: { totalBytes: number; quotaBytes: number; percentage: number; count: number; averageBytes: number; largestBytes: number; orphanCount: number; orphanBytes: number }; assets: { id: string; originalFilename: string | null; sizeBytes: number; width: number; height: number; createdAt: string; contentUrl: string; references: { entityName: string; fieldName: string }[] }[] };
export function StorageDashboard() {
  const [data, setData] = useState<Data>(); const [showImages, setShowImages] = useState(false); const [sort, setSort] = useState<"size" | "newest">("size");
  async function load(nextSort = sort) { setData(await fetch(`/api/media?sort=${nextSort}`).then((response) => response.json())); }
  useEffect(() => { fetch(`/api/media?sort=${sort}`).then((response) => response.json()).then(setData); }, [sort]);
  async function cleanup() { if (!data?.stats.orphanCount || !window.confirm(`사용되지 않는 이미지 ${data.stats.orphanCount}개를 저장소와 DB에서 삭제할까요?`)) return; const response = await fetch("/api/media/cleanup", { method: "POST" }); if (!response.ok) { window.alert("사용되지 않는 이미지를 정리하지 못했습니다."); return; } await load(); }
  if (!data) return <p className="muted">Storage 정보를 불러오는 중…</p>;
  return <div className="storage-dashboard"><div className="storage-usage"><div><span>Images</span><strong>{bytes(data.stats.totalBytes)} / {bytes(data.stats.quotaBytes)}</strong></div><span>{data.stats.percentage.toFixed(1)}%</span></div><div className="storage-progress"><i style={{ width: `${Math.min(100, data.stats.percentage)}%` }}/></div><div className="storage-metrics"><div><span>Images</span><strong>{data.stats.count}</strong></div><div><span>Average</span><strong>{bytes(data.stats.averageBytes)}</strong></div><div><span>Largest</span><strong>{bytes(data.stats.largestBytes)}</strong></div></div><div className="storage-actions"><button onClick={() => setShowImages((value) => !value)}><Images size={15}/> {showImages ? "Hide images" : "View images"}</button><div><span>Unused images<br/><small>{data.stats.orphanCount} files · {bytes(data.stats.orphanBytes)}</small></span><button className="danger" disabled={!data.stats.orphanCount} onClick={() => void cleanup()}><Trash2 size={14}/> Clean up</button></div></div>{showImages ? <div className="media-library"><header><strong>Images</strong><select value={sort} onChange={(event) => setSort(event.target.value as "size" | "newest")}><option value="size">Size descending</option><option value="newest">Newest</option></select></header>{data.assets.length ? data.assets.map((asset) => <div className="media-row" key={asset.id}><img src={asset.contentUrl} alt="저장 이미지 미리보기"/><span><strong>{asset.originalFilename || "image"}</strong><small>{asset.width} × {asset.height} · {bytes(asset.sizeBytes)} · {new Date(asset.createdAt).toLocaleDateString("ko-KR")}</small><em>{asset.references.length ? asset.references.map((reference) => `${reference.entityName} / ${reference.fieldName}`).join(" · ") : "사용되지 않음"}</em></span></div>) : <p className="muted">저장된 이미지가 없습니다.</p>}</div> : null}</div>;
}
function bytes(value: number) { if (value < 1024) return `${value} B`; if (value < 1024 ** 2) return `${(value / 1024).toFixed(1)} KB`; if (value < 1024 ** 3) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${(value / 1024 ** 3).toFixed(2)} GB`; }
