"use client";
import { FormEvent, useEffect, useState } from "react";
import type { UserRole } from "@/lib/db/schema";

type ListedUser = { id: string; name: string; email: string; emailVerified: boolean; role: UserRole; createdAt: string };
type Invitation = { id: string; email: string; createdAt: string; expiresAt: string; acceptedAt: string | null };

export function UsersSettings({ currentUserId }: { currentUserId: string }) {
  const [users, setUsers] = useState<ListedUser[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [email, setEmail] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function load() { const [usersResponse, invitationsResponse] = await Promise.all([fetch("/api/admin/users"), fetch("/api/admin/invitations")]); if (usersResponse.ok) setUsers(await usersResponse.json()); if (invitationsResponse.ok) setInvitations(await invitationsResponse.json()); }
  useEffect(() => { void load(); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); if (pending) return; setPending(true); setError(""); const response = await fetch("/api/admin/invitations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const body = await response.json(); setPending(false); if (!response.ok) return setError(body.error ?? "Could not create invitation"); setEmail(""); await load(); }
  async function changeRole(userId: string, role: UserRole) { setError(""); const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, role }) }); const body = await response.json(); if (!response.ok) return setError(body.error ?? "Could not update role"); setUsers((all) => all.map((item) => item.id === userId ? { ...item, role } : item)); }
  return <div className="settings-stack"><section className="panel"><h2>Invite user</h2><p className="muted">Invitations are valid for 7 days and can be used once.</p><form className="invite-form" onSubmit={invite}><label className="field"><span>Email</span><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)}/></label><button className="button" disabled={pending}>{pending ? "Inviting…" : "Create invitation"}</button></form>{error && <p className="form-error">{error}</p>}</section><section className="panel"><h2>Existing users</h2><div className="user-list">{users.map((item) => <div className="user-row" key={item.id}><div><strong>{item.name}</strong><span>{item.email} · {item.emailVerified ? "Verified" : "Unverified"}</span></div><select aria-label={`Role for ${item.name}`} value={item.role} disabled={item.id === currentUserId} onChange={(event) => changeRole(item.id, event.target.value as UserRole)}><option value="editor">Editor</option><option value="admin">Admin</option></select></div>)}</div></section><section className="panel"><h2>Invitations</h2><div className="user-list">{invitations.length ? invitations.map((item) => <div className="user-row" key={item.id}><div><strong>{item.email}</strong><span>{item.acceptedAt ? "Accepted" : new Date(item.expiresAt) < new Date() ? "Expired" : `Expires ${new Date(item.expiresAt).toLocaleDateString()}`}</span></div></div>) : <p className="muted">No invitations yet.</p>}</div></section></div>;
}
